### ISSUE TITLE
https don't work.

### ISSUE THREAD

**Issue by redpixy** [openspeedtest/Speed-Test#1]
Hi, tried using adding this to my build with the path of where my cert and key were, -v /PATH-TO-YOUR-OWN-SSL-CERTIFICATE**:/etc/ssl/**. However I couldn't seem to get the https working. Is there something I'm missing. My key and cert are "fastpe.cert" and "fastpe.key". These cert and key are working on my other applications.

**Comment by openspeedtest** [comment]
Try rename it as  nginx.crt and nginx.key & Follow the instructions below. 

You can mount a folder with your own SSL certificate to this docker container by adding the following line to the above command.

-v /PATH-TO-YOUR-OWN-SSL-CERTIFICATE**:/etc/ssl/**

I am adding a folder with **nginx.crt and nginx.key** from my desktop by using the following command.

**Comment by redpixy** [comment]
would it be possible to edit the config file or use the -e to point application to the cert and key?

**Comment by openspeedtest** [comment]
/etc/nginx/conf.d/

you can edit OpenSpeedTest-Server.conf
and change to  nginx.crt and nginx.key to something else. 
What is stoping you from renaming the key and crt?

**Comment by redpixy** [comment]
Thanks. Finally gotten to work. Strangely after editing the OpenSpeedTest-Server.conf and rebooting, the log shows permission deny to the OpenSpeedTest-Server.conf file. I had to change the permission of the file to 744 to have it working.

**Comment by openspeedtest** [comment]
New features:


1) Stress Test. (Continuous Speed Test)
Stress testing is for identifying overheating issues & other problems that may arrive when the system is at full load. So you can ensure stability when used in a normal environment.

You can see the results in near-real-time, So you can test and see the impact of the configuration change in your network equipment instantly, Helpful when Fixing Wi-Fi interference , change in position or orientation, proper ventilation, etc., from your devices easily.

Overheating and thermal throttling is common issues found on all network equipment and connected devices. if you run a stress test, you can simulate a busy day and see how your device will perform.

1) Download and install OpenSpeedTest-Server <https://go.openspeedtest.com/Server>

2) Open the URL shown in Server App on the device you want to run the test.

3) To enable stress pass 'Stress' or 'S' keyword as a URL parameter. Also you can feed the first letter of each parameter and its values. You can pass multiple keywords and it's not CasESensitivE. 

Example :

if http://192.168.1.5:3000 is the url shown in server.

You need to add "?Stress=Low" at the end of the url or "?S=L"

Now, the URL looks like this. 

http://192.168.1.5:3000?Stress=Low or http://192.168.1.5:3000?S=L

Stress=Low Or S=L will run a speed test for 5 Minutes (300 Seconds) for upload and download.

Stress=Medium Or S=M will run run a speed test for 10 Minutes (600 Seconds) for upload and download.

Stress=High Or S=H will run run a speed test for 15 Minutes (900 Seconds) for upload and download.

Stress=VeryHigh Or S=V will run a speed test for 30 Minutes (1800 Seconds) for upload and download.

Stress=Extreme Or S=E will run a speed test for 60 Minutes (3600 Seconds) for upload and download.

Stress=Day Or S=D will run a speed test for one Day (86400 Seconds) for upload and download.

Stress=Year Or S=Y will run a speed test for one Year (31557600 Seconds) for upload and download.

or you can specify "Stress=5000" or "S=5000", This will run a speed test for 5000 Seconds, or any other number of your choice.

2) Start a Speed Test Automatically.

If you want to start the test automatically without clicking the start button, add "run" or "r" keyword as a URL parameter.

http://192.168.1.5:3000?run or http://192.168.1.5:3000?R

If you like to start the test after specific time, give the time in seconds.

Example, If i need to run a speed test after 45 seconds

http://192.168.1.5:3000?run=45

If i need to stress for 300 seconds and start a speed test without clicking the start button.

http://192.168.1.5:3000?R&S=300 or http://192.168.1.5:3000?Run&Stress=300

3) Run a Specific Test. (Download, Upload or Ping.)

Sometimes you need to run a specific test, If you need to run upload test, you can pass "Test=Upload" or "T=U" as a URL Parameter. You can test download  "Test=Download" or "T=D" or ping  "Test=Ping" or "T=P" like this. 

4)Set the Number of ping samples by adding "Ping" or "P" as a URL Parameter

http://192.168.1.5?Ping=500 OR http://192.168.1.5?p=500

More samples means more accurate representation. Ping=500 will send 501 requests to server to find the accurate ping value.

5) Change default limit of 6 parallel http connections to Server, by adding "XHR" or "X" as a URL Parameter

http://192.168.1.5?Xhr=1 OR http://192.168.1.5?X=1

6 is the common limit found on most browser. XHR will Accept values above 1 and maximum 32

6) Select a different server to run a speed test.

http://192.168.1.5?Host=http://192.168.55.1:90 OR http://192.168.1.5?h=http://192.168.55.1:90

Pass "Host" or "H" as a URL Parameter. Accept only valid http urls like "http://192.168.1.10:3000" or "https://yourHost.com".

7) Set a PingTimeout dynamically by passing "Out" or "o" as a URL Parameter

http://192.168.1.5?Out=7000 OR http://192.168.1.5?O=7000

If Server not responded within 5 Seconds for any requests we send ('pingSamples' times) We will show Network Error, you can change the limit here. In milliseconds, if you need to set 6 seconds. Change value to 6000.

8) Disable or change Overhead Compensation factor.

http://192.168.1.5?Clean or http://192.168.1.5?C

Overhead Compensation factor, This is browser based test, Many Unknowns. Currently 4%. That is within the margin of error. You can pass "Clean" or "C" as a URL Parameter and reset Overhead Compensation factor to Zero or set any value between 0 and 4. 1 = 1% to 4 = 4%. "clean" will not accept values above 4, so Compensation is limited to maximum 4%.

Use Google Chrome, Chromium, Edge, Opera, Brave, Safari etc. If the stress test is longer than 15 minutes or speed is 2.5Gbps or more. 

This test can run on any browser that is IE10 or new. Firefox is still showing memory leak, use it only if you are testing speeds less than 2.5 Gbps and duration is less than 10 minutes.

Remove that lousy network equipment. That creates unnecessary problems at unexpected times on your network. Test your equipment now and improve your network infrastructure.

An internet speed test alone will not tell you the whole story. If you need solid performance, you need to make your network reliable. For that, you need to invest in good network equipment, configure them correctly and deploy them after load testing.

Previously, our internet speed was significantly less. Now it's approaching 1Gbps, and people started using network-attached storage and other network-heavy equipment at home. So today's homes need enterprise-level network infrastructure. That is why I said, "An internet speed test alone will not tell you the whole story."
