### ISSUE TITLE
FEATURE: Server name to be displayed on UI

### ISSUE THREAD

**Issue by alexruffell** [openspeedtest/Speed-Test#102]
I have installed OST on several machines on my LAN and since they all look the same, I need to go by the IP of the server. It would be nice if there were a way to configure a server name that is displayed on the UI for easy identification of the server.

**Comment by openspeedtest** [comment]
Docker?

**Comment by alexruffell** [comment]
Yes, i use the docker method to install as recommended on your website. Why? The installs are on 3 Proxmox makeshift servers.

**Comment by openspeedtest** [comment]
The requested feature is already on my to-do list. However, I have no plans to add this to desktop and mobile apps, which is why I asked specifically. I am currently busy with other important tasks, but I will add this feature to our Docker container after October 25, 2023. Thanks.

**Comment by openspeedtest** [comment]
@alexruffell 

Added `SET_SERVER_NAME`

```
docker run --restart=unless-stopped -e SET_SERVER_NAME=HOME-NAS --name=openspeedtest -d -p 3000:3000 openspeedtest
````

<img width="1680" alt="Screenshot 2023-10-31 at 8 35 36 AM" src="https://github.com/openspeedtest/Speed-Test/assets/51720450/f0a51332-eab6-4cc2-8805-0c56c93f16d9">
<img width="1680" alt="Screenshot 2023-10-31 at 8 35 26 AM" src="https://github.com/openspeedtest/Speed-Test/assets/51720450/456b0763-48ed-4c22-9396-6a35536ac875">

**Comment by alexruffell** [comment]
Likely me not knowing how to use docker, but I had to stop the container and then remove both the container and the image otherwise it would not pull the latest version. I also had to add `latest` to the CLI command you provided above. It works great all on 3 of my internal servers! Thanks!
