### ISSUE TITLE
Privacy policy for the embedded version

### ISSUE THREAD

**Issue by Eimji** [openspeedtest/Speed-Test#108]
Hello,

Thanks for your great work. I plan to embed openspeed in a mobile application. I would like to know about the privacy policy. Which data is collected ?

Thanks

**Comment by openspeedtest** [comment]
Use https://github.com/openspeedtest/Speed-Test on your own server; it does not collect any data.

**Comment by Eimji** [comment]
Thanks for your answer.

**Comment by xpufx** [comment]
> Use https://github.com/openspeedtest/Speed-Test on your own server; it does not collect any data.

The icons at the bottom take the user to the openspeedtest website. I can see from the url that the data is actually probably going there just for display purposes, but that also gives you the opportunity to collect it. Would it be possible to do the display locally. Failing that, is there a way to disable creating those links?

**Comment by openspeedtest** [comment]
@xpufx link to Openspeedtest? Guage Icon?
