### ISSUE TITLE
Unrealistic upload speeds using Safari

### ISSUE THREAD

**Issue by Steffen75** [openspeedtest/Speed-Test#11]
I'm seeing unrealistic upload speeds using the current version of Safari on my iPhone and my Mac.

I have a small virtual machine using Debian 11 with Nginx as webserver for hosting openspeedtest on my internal network. The wired network speed is 1 Gbit/s.

Now when I run openspeedtest on my Mac (wired connection) using Safari I get completely unrealistic upload speeds (left side of the screenshot). But when I do the same thing using Firefox everything is plausible regarding the upload speed (right side of the screenshot).

<img width="1740" alt="Safari-Firefox" src="https://user-images.githubusercontent.com/18570579/154670804-a6174bae-a347-4fb9-a165-908d6e9f98af.png">

Using an iPhone and wifi is pretty much the same. For example my older iPhone 7 reports 210 Mbps as download and 4728 Mbps as upload.

I have turned off GZIP in the config file of Nginx. But the mystery remains.

What's wrong here?

**Comment by openspeedtest** [comment]
Delete browser cache or try in private window. Did you used previous version on the same IP address / ports?One of my friend reported an issue like this but after deleting cache/running from private window solved the issue. If the problem still exists, take a look at Safari browser console. Must be server configuration error. Did you try Openspeedtest-server or docker image? And able to reproduce this issue? On 18 Feb 2022 4:53 pm, Steffen75 ***@***.***> wrote:
I'm seeing unrealistic upload speeds using the current version of Safari on my iPhone and my Mac.
I have a small virtual machine using Debian 11 with Nginx as webserver for hosting openspeedtest on my internal network. The wired network speed is 1 Gbit/s.
Now when I run openspeedtest on my Mac (wired connection) using Safari I get completely unrealistic upload speeds (left side of the screenshot). But when I do the same thing using Firefox everything is plausible regarding the upload speed (right side of the screenshot).

Using an iPhone and wifi is pretty much the same. For example my older iPhone 7 reports 210 Mbps as download and 4728 Mbps as upload.
I have turned off GZIP in the config file of Nginx. But the mystery remains.
What's wrong here?

**Comment by Steffen75** [comment]
I found the problem. Safari's console was reporting HTTP errors 405 during the upload due to the static design of OST.

So I added _error_page  405     =200 $uri;_ to the config and now it works.

But what about adding a server side php script for making a real upload to /dev/null as an improvement in a future version. Using PUT should make it rather simple.

**Comment by openspeedtest** [comment]
Nginx will read the post body and pass it to static file. It will get discarded like dev/null. 

Yes we can use PHP or any other languages to do the same stuff. 

But static design means you don't have to worry about security updates for your programming language. 

More secure, easy to deploy, run anywhere all you need is basic web server. 

That is why I am able to create Android and iOS apps with the same files that is posted here. 

If it does what we need means why should we need a programming language like PHP anyway.

**Comment by openspeedtest** [comment]
New features:


1) Stress Test. (Continuous Speed Test)
Stress testing is for identifying overheating issues & other problems that may arrive when the system is at full load. So you can ensure stability when used in a normal environment.

You can see the results in near-real-time, So you can test and see the impact of the configuration change in your network equipment instantly, Helpful when Fixing Wi-Fi interference , change in position or orientation, proper ventilation, etc., from your devices easily.

Overheating and thermal throttling is common issues found on all network equipment and connected devices. if you run a stress test, you can simulate a busy day and see how your device will perform.

1) Download and install OpenSpeedTest-Server <https://go.openspeedtest.com/Server>

2) Open the URL shown in Server App on the device you want to run the test.

3) To enable stress pass 'Stress' or 'S' keyword as a URL parameter. Also you can feed the first letter of each parameter and its values. You can pass multiple keywords and it's not CasESensitivE. 

Example :

if http://192.168.1.5:3000 is the url shown in server.

You need to add "?Stress=Low" at the end of the url or "?S=L"

Now, the URL looks like this. 

http://192.168.1.5:3000?Stress=Low or http://192.168.1.5:3000?S=L

Stress=Low Or S=L will run a speed test for 5 Minutes (300 Seconds) for upload and download.

Stress=Medium Or S=M will run run a speed test for 10 Minutes (600 Seconds) for upload and download.

Stress=High Or S=H will run run a speed test for 15 Minutes (900 Seconds) for upload and download.

Stress=VeryHigh Or S=V will run a speed test for 30 Minutes (1800 Seconds) for upload and download.

Stress=Extreme Or S=E will run a speed test for 60 Minutes (3600 Seconds) for upload and download.

Stress=Day Or S=D will run a speed test for one Day (86400 Seconds) for upload and download.

Stress=Year Or S=Y will run a speed test for one Year (31557600 Seconds) for upload and download.

or you can specify "Stress=5000" or "S=5000", This will run a speed test for 5000 Seconds, or any other number of your choice.

2) Start a Speed Test Automatically.

If you want to start the test automatically without clicking the start button, add "run" or "r" keyword as a URL parameter.

http://192.168.1.5:3000?run or http://192.168.1.5:3000?R

If you like to start the test after specific time, give the time in seconds.

Example, If i need to run a speed test after 45 seconds

http://192.168.1.5:3000?run=45

If i need to stress for 300 seconds and start a speed test without clicking the start button.

http://192.168.1.5:3000?R&S=300 or http://192.168.1.5:3000?Run&Stress=300

3) Run a Specific Test. (Download, Upload or Ping.)

Sometimes you need to run a specific test, If you need to run upload test, you can pass "Test=Upload" or "T=U" as a URL Parameter. You can test download  "Test=Download" or "T=D" or ping  "Test=Ping" or "T=P" like this. 

4)Set the Number of ping samples by adding "Ping" or "P" as a URL Parameter

http://192.168.1.5?Ping=500 OR http://192.168.1.5?p=500

More samples means more accurate representation. Ping=500 will send 501 requests to server to find the accurate ping value.

5) Change default limit of 6 parallel http connections to Server, by adding "XHR" or "X" as a URL Parameter

http://192.168.1.5?Xhr=1 OR http://192.168.1.5?X=1

6 is the common limit found on most browser. XHR will Accept values above 1 and maximum 32

6) Select a different server to run a speed test.

http://192.168.1.5?Host=http://192.168.55.1:90 OR http://192.168.1.5?h=http://192.168.55.1:90

Pass "Host" or "H" as a URL Parameter. Accept only valid http urls like "http://192.168.1.10:3000" or "https://yourHost.com".

7) Set a PingTimeout dynamically by passing "Out" or "o" as a URL Parameter

http://192.168.1.5?Out=7000 OR http://192.168.1.5?O=7000

If Server not responded within 5 Seconds for any requests we send ('pingSamples' times) We will show Network Error, you can change the limit here. In milliseconds, if you need to set 6 seconds. Change value to 6000.

8) Disable or change Overhead Compensation factor.

http://192.168.1.5?Clean or http://192.168.1.5?C

Overhead Compensation factor, This is browser based test, Many Unknowns. Currently 4%. That is within the margin of error. You can pass "Clean" or "C" as a URL Parameter and reset Overhead Compensation factor to Zero or set any value between 0 and 4. 1 = 1% to 4 = 4%. "clean" will not accept values above 4, so Compensation is limited to maximum 4%.

Use Google Chrome, Chromium, Edge, Opera, Brave, Safari etc. If the stress test is longer than 15 minutes or speed is 2.5Gbps or more. 

This test can run on any browser that is IE10 or new. Firefox is still showing memory leak, use it only if you are testing speeds less than 2.5 Gbps and duration is less than 10 minutes.

Remove that lousy network equipment. That creates unnecessary problems at unexpected times on your network. Test your equipment now and improve your network infrastructure.

An internet speed test alone will not tell you the whole story. If you need solid performance, you need to make your network reliable. For that, you need to invest in good network equipment, configure them correctly and deploy them after load testing.

Previously, our internet speed was significantly less. Now it's approaching 1Gbps, and people started using network-attached storage and other network-heavy equipment at home. So today's homes need enterprise-level network infrastructure. That is why I said, "An internet speed test alone will not tell you the whole story."

**Comment by arekm** [comment]
Why 405 response POST entries are taken into account anyway? These are errors and maybe should be shown to user instead of being counted for upload speed.

![speedtest-bug-1](https://github.com/openspeedtest/Speed-Test/assets/50869/49240027-efb7-49c5-b638-ecaba8ac6ef0)

**Comment by openspeedtest** [comment]
@arekm Some browsers, like Safari, may not trigger the onload event if the request completes in under 100 milliseconds. This is a known issue with Safari and Internet Explorer (IE). Therefore, when testing very fast connections, we might not receive the onload event, prompting us to calculate it manually. This behavior is only likely to occur if the server is not configured correctly and is generally not encountered in standard use.

**Comment by arekm** [comment]
I'm using google chrome 122 (and the server isn't configured for speedtest purposes, that's for sure).

**Comment by openspeedtest** [comment]
@arekm Which Server? If that is Nginx check https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf#L29 If that is not Nginx, Handle /upload and return 200.

**Comment by arekm** [comment]
Configuration of that server cannot be changed (it's autogenerated nginx config from pfSense software for purposes of pfSense panel management only and speed test is only sneaked into it to be able to test speeds to/from pfSense router).

I'm only mentioning that problem to see if there is a way to better handle 405 error in such "not correctly configured server c" case, instead of showing up crazy results.

**Comment by openspeedtest** [comment]
@arekm Even when the server is configured correctly, Safari at very high speeds can exhibit this behavior. Otherwise, we would need to drop support for Safari, which is not an option. Unfortunately, I am not aware of a better way to avoid this issue.

**Comment by openspeedtest** [comment]
@arekm Maybe we can stop the upload process and warn the user if the server returns a 405 (Method Not Allowed) status code.
 
````
if (xhr.status === 405) {
    // Handle the 405 error
    console.error("Error: Method Not Allowed (405)");
````
I will test this, and if possible, I will update the speed test soon.
