### ISSUE TITLE
testing limit

### ISSUE THREAD

**Issue by susantha1995** [openspeedtest/Speed-Test#12]
hi, 

is there any limit to checking the speed test? for example, if my site gets 100,000 visitors daily to test speed test, will it work out properly without problem? (if I have unlimited bandwidth)  or does it need an API?

**Comment by openspeedtest** [comment]
I never imagined something like that, If you have the resources you can do as much as you like.. 
You need to scale properly.

**Comment by susantha1995** [comment]
ok, thank you. also, can you tell me what is the "downloading" file? my hosting server is limited to 25MB for writing/uploading a single file size to the server.  should I upload that "downloading" file also to work properly? is there any way to reduce that file size to less than 25MB ??

**Comment by openspeedtest** [comment]
Your hosting provider?
Server need to respond like [this](https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf)  
So you should have some level of control. 
You can use "downloading" file that is 20 or 25Mb. 
But why? You should change your hosting provider. 
Unlimited bandwidth alone will not "RUN" a successful website or app.
You need Good amount of CPU and RAM, One Server is not enough for everyone in the world, so you need to cache or replicate your service in every region that is critical.

**Comment by openspeedtest** [comment]
Using docker image? 

If not

Server Requirements
Nginx, Apache, IIS, Express, or Any Web server that supports HTTP/1.1.

Accept, GET, POST, HEAD & OPTIONS, Response 200 OK.
Accept, POST to Static Files, Response 200 OK.
Timeout greater than 60 seconds.
Disable Access logs for Increasing server performance.
Improve Time to First Byte (TTFB)
[Follow our Nginx Config.](https://github.com/openspeedtest/Nginx-Configuration)


YOU MUST ENABLE  POST to Static Files with content length 35Mb or more.
