### ISSUE TITLE
[Challenge] Run OpenSpeedTest on Ubuntu Server

### ISSUE THREAD

**Issue by Ashkaan** [openspeedtest/Speed-Test#124]
I'm trying to keep a OST as a headless server running 24/7.  I have an Ubuntu 22 server that would be a perfect fit.  I want to run it locally and natively (no containers).

I've tried every method mentioned here to install and it doesn't work.  The snap package requires a UI (it seems).  I installed nginx, using your configs, but can't get the app to run for the config to take hold.

Can you please give us some step-by-step instructions for getting this online?

**Comment by openspeedtest** [comment]
Install Nginx
copy https://github.com/openspeedtest/Speed-Test to www folder
copy https://github.com/openspeedtest/Nginx-Configuration to /etc/nginx/

**Comment by Ashkaan** [comment]
Thank you!
