### ISSUE TITLE
Getting canceled and failed uploads and downloads

### ISSUE THREAD

**Issue by Aerofolio** [openspeedtest/Speed-Test#128]
I'm testing the application in my local machine and asking for other people in the same network as me to run it and they sent me those prints:
![image](https://github.com/openspeedtest/Speed-Test/assets/84919843/8cc6733d-2245-4d18-a93c-f41b861407b7)
![image](https://github.com/openspeedtest/Speed-Test/assets/84919843/736a0eec-209b-4f78-bfdd-d9274d4f7b66)
![image](https://github.com/openspeedtest/Speed-Test/assets/84919843/f3c9427a-f3bd-4148-8a73-d96a65bc8cac)

So i noticed the flat parts of the graph and analised the http requests, some of them are being canceled or are failing:
![image](https://github.com/openspeedtest/Speed-Test/assets/84919843/712719f0-7279-4faa-89f6-6a724176266f)
![image](https://github.com/openspeedtest/Speed-Test/assets/84919843/c3c7383d-bf0a-4d01-9098-25fe65bd8f29)

I'm not very used to work with docker so there's a high chance that i'm missing something

**Comment by openspeedtest** [comment]
Reverse proxy? Try without a reverse proxy.

**Comment by Aerofolio** [comment]
Yeah, i've checked nginx configurations and started host in a proper server, that solved most of my issues. The only details that are still looking strange are: 
- Very long time to start measuring downoad, it stucks with the 'initializing' text.
- 0.000 Mbps UPLOAD Speed.

**Comment by openspeedtest** [comment]
Post more details about your setup. 

- cleint browser / cpu / ram / os / extensions/ other software 
- server nic / os etc. 
- network layout, router, cables 

Maybe bad cable can be a problem, try known working cable. Install latest NIC driver , install opera or Ms Edge. 

## Run our docker image on your sever.

**Comment by Aerofolio** [comment]
I've managed to fix my issues, they were mainly from my inexperience with nginx. Thank you for the support.
