### ISSUE TITLE
Does Openspeedtest support 2.5+Gbps?

### ISSUE THREAD

**Issue by araheems** [openspeedtest/Speed-Test#132]
Hi Team,
We have installed this Openspeedtest server application in 10Gpbs supported hardware. But we are less than 1Gbps for Download and upload speed is as expected 2.2Gbps. I can confirm that configurations in the network all good to support 2.5Gbps download and upload.
We want to understand if the free version of this openspeedtest server supports 2.5Gbps on download?

![IMG_0965](https://github.com/openspeedtest/Speed-Test/assets/163519149/e49f416c-48b6-4af1-bf87-e4bfc348c363)

**Comment by openspeedtest** [comment]
This is a VM? VMs may not get enough CPU time. Run it on a real Mac. If this is a real Mac, make sure it's from 2019 or newer; old CPUs are not good enough for 10Gbps. It looks like a driver issue if everything else is perfect. Also, enable jumbo frames."

**Comment by openspeedtest** [comment]
@araheems Both Docker and GUI OpenSpeedTest Server can handle 15 Gbps or more.
