### ISSUE TITLE
Insane download and upload speeds on a gig plan

### ISSUE THREAD

**Issue by MitchRapp01** [openspeedtest/Speed-Test#133]
I'm currently getting around 4500 Mbps down and about 4000 Mbps up on a gig internet plan from verizon fios.  I'm assuming there is something I haven't done correctly.  I just started using this app.  I'm not sure if there is some sort of configuration I've overlooked.  Please advise.

I'm on an msi ge68 hx running windows 11 pro.  I have a killer be1750 wifi 7 wireless card.  I've not tried using an ethernet cable as I am concerned about my wifi speed.

I tried in chrome, firefox and microsoft edge.

Speedtest.net:  Down:  502 Mbps  Up:  381 Mbps
Cloudflare:  Down:  745 Mbps  Up:  245 Mbps

![openspeedtest](https://github.com/openspeedtest/Speed-Test/assets/23629571/2654229a-3d81-4979-a460-16ba8c8e86d2)

**Comment by openspeedtest** [comment]
So you ran the OpenSpeedTest Server on your machine and then visited the URL shown in the server from the same machine using a browser, correct? Thus, you are testing the localhost speed. The OpenSpeedTest Server is designed for testing speed between two devices on the same network. To measure your Wi-Fi speed, run the OpenSpeedTest Server on a device directly connected to your router and visit the URL shown in the server app from your mobile phone.

**Comment by MitchRapp01** [comment]
That works better.  So if I run the server from my pc and enter the url and port on my phone it shows the wifi speed of my computer or my phone?  Also, why do you think my download speed is so much faster on cloudflare than on openspeedtest?  After following your advice I got a download speed of about 333 Mbps.

**Comment by openspeedtest** [comment]
If your PC is connected directly to the router and you tested using your phone, then that reflects the maximum Wi-Fi speed your phone can achieve in that location. However, the speed will likely be different if you move to another room. Wi-Fi speed depends on many factors. Changing the channel, switching to 5 GHz, and repositioning your Wi-Fi router can all help improve your Wi-Fi speed.

**Comment by MitchRapp01** [comment]
Thanks so much!  :)
