### ISSUE TITLE
[ It was False Positive ] OpenSpeedTest-Server 2.1.8_ia32.exe For Windows x86-32 flagged as virus

### ISSUE THREAD

**Issue by MadMark13** [openspeedtest/Speed-Test#134]
Download attempt from https://openspeedtest.com/selfhosted-speedtest
OpenSpeedTest-Server 2.1.8_ia32.exe For Windows x86-32 

Keeps tripping Avast Win32:Malware-gen infection filter.

The other ones
OpenSpeedTest-Server 2.1.8.exe For Windows X86-64
OpenSpeedTest-Server 2.1.8_arm64.exe For Windows ARM-64
were ok.

**Comment by openspeedtest** [comment]
This is an Electron app. It's either a false positive or some dependencies, specifically 32-bit ones, might be deprecated. Time to drop 32-bit support.

**Comment by openspeedtest** [comment]
@MadMark13 These apps have been online (same version) since February 2023. They're now a year old, and this is the first time we've seen this kind of report.

**Comment by openspeedtest** [comment]
@MadMark13 Microsoft Store is also distributing the same app. So, this must be a false positive.

**Comment by openspeedtest** [comment]
@MadMark13 Update your antivirus software and test again. It's now classified as a PUP (Potentially Unwanted Program), not a virus anymore. You can check Virus Total for confirmation.

**Comment by openspeedtest** [comment]
Now it's not PUP... 

````
Thank you for your email. 

Avast PUP team reviewed your file SHA 8a2782c9249b3f4cbd7ae962df81e47c5a7670ae888b9e0718764190c3401181, and they cleaned the reputation in our database. Please, be patient. The application will stop being blocked within 24 hours.

I apologize for the inconvenience caused.
````
