### ISSUE TITLE
Slow dowload speeds

### ISSUE THREAD

**Issue by TheCableGuy99** [openspeedtest/Speed-Test#135]
Hi,

I'm wondering why my PC always reports 2/3rds the possible download speed and the full speed for uploads?

The whole network is 10Gbps except for my laptop which is 2.5Gbps. There's no background traffic and the upload results show the NIC is more than able to do the full 2.5Gbps. 

I've seen other posts asking the same but there doesn't seem to be anyone getting any answers. Could it be a bug? Is anyone getting symmetrical uploads and downloads on a LAN test?

It's installed on a docker and connected with to the network with LACP (2x 10Gbps) so more than enough bandwidth to do a 2.5Gbps test.

Thanks for any help.

![Screenshot 2024-03-31 120917](https://github.com/openspeedtest/Speed-Test/assets/39552752/45fa9c58-0b67-400b-923c-61d643350ce8)

**Comment by openspeedtest** [comment]
@TheCableGuy99 Enabled Hyper V? Check https://youtu.be/2u0AuNF8e_E?si=5nmtz1yFfsE-9VZp
Use Google Chrome, enable Jumbo Frames, check NIC Driver, and ensure that your client is using a modern CPU from 2017 or newer, with a Geekbench 6 score of 1300 or higher for single core (such as Ryzen 3000 or newer, Apple M1 or newer). Older CPUs can achieve their maximum potential when used with Chrome and Ubuntu.
