### ISSUE TITLE
Provide original source code to app.js

### ISSUE THREAD

**Issue by PedroHase** [openspeedtest/Speed-Test#14]
### Description of the Issue

Currently, only a minified version of app.js (which contains all application logic) is provided. Even if prettified / de-minified using tools like [unminify.com](https://unminify.com/), it is close to impossible (without spending hours of decrypting) to understand the code.

<details>
<summary>Example for unminified code</summary>

```js
// ...
(function (bb) {
    function g(a) {
        if (!(this instanceof g)) return new g(a);
        this.el = document.getElementById(a);
    }
    var n,
        Ha,
        Ia = function (a) {
            a && "function" === typeof a && a();
        };
    g.prototype.fade = function (a, c, f) {
        var e = "in" === a,
            t = e ? 0 : 1,
            w = 14 / c,
            m = this;
        e && ((m.el.style.display = "block"), (m.el.style.opacity = t));
        var p = window.setInterval(function () {
            t = e ? t + w : t - w;
            m.el.style.opacity = t;
            0 >= t && (m.el.style.display = "none");
            (0 >= t || 1 <= t) && window.clearInterval(p, Ia(f));
        }, 14);
    };
//...
```
As can be seen, even if unminified, variable names have been substituted with letters, the code structure has been significantly changed and the logic is very hard to decypher.
</details>

This basically turns the app into a black box and makes it close to impossible to review & inspect the code, behavior, internals, etc. Essentially this renders this project more or less into a closed-source app as this is similar to sharing an executable instead of the source code.

### Suggested Solution

Please include the full original source code to `app.js`. This will help build trust into this project and opens the possibility for potential outside collaborators to join this project (e.g. fixing bugs, improving the code, add new features, etc).

**Comment by openspeedtest** [comment]
I am planning to do just that, but original code i have written in 2011 still exists, i need to refactor it before making it public. Now i need to spend few hours to understand, how and why i have written certain functions like the way it is. poor comments, no js conventions, My Own Implementation of MVC :) etc.

**Comment by markfrancisonly** [comment]
@openspeedtest The creative commons license for no-derivatives is out of place in github, and against the spirit of open source collaborative software development in general. your solution is useful, beautiful and functions well, but you should either release your source code and change the license, or take down your repository from github imo

**Comment by openspeedtest** [comment]
By definition now it's not " open source collaborative software development in general " that is why CC. 
In near future i am planning to change this. For a full refactoring, need time, it will also introduce new bugs.  Currently it's not a priority for this project. If you need a different license write to support@openspeedtest.com , now am learning new stuff now, working on new projects etc. "take down your repository from github" really CC project should not exists on GitHub? I don't know..

**Comment by markfrancisonly** [comment]
>  CC project should not exists on GitHub
Yes in fact CC projects do not belong on Github because people cannot fork a CC project. Your solution isn't open, it's freeware....  and this should be a github policy violation.

I've been in this business a long time. The best reason to not release your code is not because you are embarrassed that your code needs improvement, the most likely reason is because either you have no intention of sharing and/or because sections of the code are stolen.

**Comment by filerun** [comment]
Not so Open is it :)

**Comment by openspeedtest** [comment]
@markfrancisonly I have no intention to share the code. Is that a problem?

**Comment by openspeedtest** [comment]
Please don't waste more time here..
