### ISSUE TITLE
[Feature Request] Bufferbloat implementation

### ISSUE THREAD

**Issue by ma-karai** [openspeedtest/Speed-Test#17]
Would there be a possibility to implement a bufferbloat test? ( see https://www.bufferbloat.net/projects/ )

**Comment by openspeedtest** [comment]
Added to my Todo list, I will consider this when i develop next major version 
currently you can run a stress test on one browser window 
http://xxx.xxx.xxx.xxx:3000?s=y
and run ping test on another window 
http://xxx.xxx.xxx.xxx:3000?t=p&p=300
you can see the added latency
