### ISSUE TITLE
How about unix CLI version? - Feature Request

### ISSUE THREAD

**Issue by xsherlockpl** [openspeedtest/Speed-Test#2]
Love it, so much nicer then iperf, if only it had CLI version so I could use it form the remote ends of network.
And then maybe a pyhon3 wrapper so I can automate those test?
best regardas
Maciej

**Comment by openspeedtest** [comment]
I am planning to do just that. but it will take some time. currently working on PWA,CMS etc. for main site.

**Comment by captaindrb** [comment]
did anything ever happen in this regard ? i reall want to be able to capture results and i can see ho wi could do that with speedtest-cli and the ookla speedtest but i would like to do on my  self-hosted openspeedtest server...

**Comment by Ardumine** [comment]
Hi, any update? A CLI tool just like speedtest-cli but for open speed test. It would be cool if we could choose the server IP/hostname. I hope this can be added soon.
