### ISSUE TITLE
Upload speeds off by orders of magnitude

### ISSUE THREAD

**Issue by GJSchaller** [openspeedtest/Speed-Test#22]
Running OpenSpeedTest on a local server on my home LAN.  Downloads speeds clock in at just under 1 GBps, which makes sense given I am on Gigabit Ethernet.  However, upload speeds come in at 100+ GBps results.  The same issue happens when testing via WiFi from my phone.  Screenshot of result attached.

Server is TrueNAS (FreeBSD), OpenSpeedTest is cloned locally via git clone command into a directory on the web server and served via Caddy web server.

![Screen Shot 2022-08-16 at 6 01 39 PM](https://user-images.githubusercontent.com/2761607/184993407-d6d66782-e379-4a11-8957-cdd2c578cccc.png)

**Comment by openspeedtest** [comment]
Server.
Server Requirements :
Nginx, Apache, IIS, Express, or Any Web server that supports HTTP/1.1.

Accept, GET, POST, HEAD & OPTIONS, Response 200 OK.

Accept, POST to Static Files, Response 200 OK.

Timeout greater than 60 seconds.

Disable Access logs for Increasing server performance.

Improve Time to First Byte (TTFB)

Follow our Nginx Config.

**Comment by openspeedtest** [comment]
look at the browser console, 
Post request is not handled properly by your server. 
Make sure you enabled post to static files and post body content 35+ Mb.. https://github.com/openspeedtest/Nginx-Configuration

**Comment by openspeedtest** [comment]
Did you try the community plugin? It's available for TrueNas Core and Scale. It's ready to use, No manual configuration needed.

**Comment by GJSchaller** [comment]
I did, but it posed two challenges: 1) It's an additional Jail that consumes resources when I have a Caddy server / jail already running, and 2) I was having challenges setting it up behind a reverse proxy to be able to see it from the public internet.  My solution was to host it on my already public-facing Caddy server, since I could just point a subdomain to it.  The challenge at this point is figuring out how to configure Caddy to work with OpenSpeedTest properly.  I have a forum thread open on the Caddy community, but haven't gotten much traction yet.  https://caddy.community/t/configuring-caddy-for-openspeedtest/16863

**Comment by openspeedtest** [comment]
Personally i never used Caddy. And this is a configuration error. I will post a guide and send you an update if i got some time to play with Caddy. so i am closing this issue for now. because this is not an issue with speed test script itself. it is behaving the way it is designed.

**Comment by GJSchaller** [comment]
Would it be possible to take a look at https://caddy.community/t/configuring-caddy-for-openspeedtest/16863 and help them with the requirements needed to run OpenSpeedTest?  They're not familiar with it, so I am hoping the two groups working together can help resolve this and make it more accessible to more users.  Thank you!

**Comment by openspeedtest** [comment]
@GJSchaller 

Turn off GZip for " Downloading " and " Upload " files. 
Enable post to Static file for " Upload " File or location.
If you enable HTTP2 or 3 you need to proxy pass upload request to an HTTP 1.1 location. Otherwise server will not wait for post body content and return 200. You will see huge upload speed numbers like this. Disable http 2 or 3 and stick with 1.1 or proxy_pass to 1.1 location. 
We make losts of requests during test. So it's better if you disable acess logs. (Save disk io and cpu cycles) . 

Within few days I will test Cady with Openspeedtest and send you an update.

**Comment by GJSchaller** [comment]
That's wonderful, thank you!  (I will be out of town for a week, so I may be slow to reply, but this is very appreciated.)

**Comment by openspeedtest** [comment]
I try caddy, but it's not easy to write rules like Nginx. So i think running openspeedtest jail behind caddy is better option.  In that jail all we installed is Nginx. So it will not consume much resources. Even docker version consume only 4 to 10 Mb ram. I may need to spend more time with caddy to understand how it works. For now i am busy with some backend stuff. See you later.

**Comment by openspeedtest** [comment]
Check https://github.com/openspeedtest/Speed-Test/issues/67
Should work.
You need jail or docker behind caddy.
````
         reverse_proxy http://localhost:3000 {
         buffer_requests
         buffer_responses
         flush_interval -1
         max_buffer_size 35MiB
        }
````
Caddy’s file server doesn’t support file uploads. If you want to upload files, you’ll need to use another tool (and you can put Caddy as a proxy in front of it).

https://caddy.community/t/how-to-upload-a-file-via-post-and-with-auth/12279/2

**Comment by GJSchaller** [comment]
Thank you!  This seems to work well... I'm not getting results that are orders of magnitude off any more.  I need to test more thoroughly when I am home and not at work, but this looks to have helped!
