### ISSUE TITLE
shouldn't relative links be used instead of explicit?

### ISSUE THREAD

**Issue by jhaar** [openspeedtest/Speed-Test#24]
Hi there

On my home apache server, I just created /var/www/html/speedtest/ and unpacked your HTML/etc into that (so I could run it as "https://my.server/speedtest/"). But it didn't work because the HTML was looking for "/assets", "/upload", "/downloading". So I went through the files and removed the leading "/" - turning them all into relative links.

Now it works fine - so I don't see any downside? Should that be the default?

BTW it just worked - well done ;-)

**Comment by openspeedtest** [comment]
Yes, I will do it in next update. 
Thanks :)

**Comment by openspeedtest** [comment]
https://github.com/openspeedtest/Speed-Test/issues/32
