### ISSUE TITLE
[Feature Request] Set test mode with UI

### ISSUE THREAD

**Issue by ericswpark** [openspeedtest/Speed-Test#28]
Instead of having the users input options as URL parameters, maybe have a list of configuration options under the SpeedTest start button? It would help with UX since you won't have to fiddle around with the URL parameter, which gets annoying especially on mobile.

If it's a question of making it as simple as possible to use, maybe have the user scroll down a bit before the options are presented, or hide them behind an "Advanced Options" button.

**Comment by openspeedtest** [comment]
It's already on my to-do list. I think I will change the three transparent buttons above the speed test button and show some options to choose like test duration etc. But now the UI is just an SVG. We can give a couple of preset options. I don't know how to handle text input. Features like this will be added to the next major version, so I can rewrite the UI if needed. Now I am going to work on some other projects. I don't know when I can come back to this.
