### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by giss69** [openspeedtest/Speed-Test#3]
Hello,

is it possible to use another port?
3000 conflict with grafana.

thank you

**Comment by openspeedtest** [comment]
Talking about docker image? You can choose any port you need. 
docker run --restart=unless-stopped --name openspeedtest -d -p 6000:3000 -p 6001:3001 openspeedtest/latest
Now i changed the port to 6000 for http and 6001 for https. 
If you are using desktop apps you have an option in GUI for changing ports.
try https://go.openspeedtest.com/server
