### ISSUE TITLE
HTML Code uses domain root should be relative path

### ISSUE THREAD

**Issue by SteveBox0** [openspeedtest/Speed-Test#32]
Some deployments might not be at the root of the domain. Ideally the code should be using relative paths instead this way it works under sub directories, etc.

**Comment by openspeedtest** [comment]
Yes, already someone mentioned this in an issue. I will do this in next update.

**Comment by mckaygerhard** [comment]
witch commit is the solution to this issue?, you @openspeedtest  just close with any reference!

**Comment by openspeedtest** [comment]
Not yet fixed the issue. Wait for the update. Or you can do it yourself on your deployment. 
Edit css and index.html and remove first '\'
For fonts and other assets.

**Comment by klepptor** [comment]
Hi @openspeedtest 

I really appreciate your work here!

Is there any PR underway for this? At least for docker it's quite annoying to change index.hml etc. ;)

**Comment by openspeedtest** [comment]
@klepptor  Very soon. How will this affect docker? When binding domain name? Can you post your issue in more detail? 
all static assets should be like 'css/app.css' instead of '/css/app.css' right. I thought this will only affect custom deployments.

**Comment by klepptor** [comment]
@openspeedtest 

I need to deploy OpenSpeedTest in a subdir, e.g. http://myserver/speedtest

Therefore I'd like to use the docker version, behind a reverse proxy (Citrix ADC).

With absolute paths in index.html etc. most of the assets aren't loaded, but changing to relative paths in index.html etc is quite uncomfortable with docker, because you have to use volumes to get the changed files into the container. And you habve to do this again with every new version of OpenSpeedTest.

Or do I miss something here?

**Comment by openspeedtest** [comment]
@klepptor No, You are correct. I never think about Sub Directory. I will fix this within two days. Thanks for posting the context.

**Comment by openspeedtest** [comment]
@klepptor I updated Docker Image. Please check it and let me know if there is any problem.

**Comment by klepptor** [comment]
@openspeedtest 

I just tested the new docker image:

in index.html you missed one absolute path:

``<object style="visibility:hidden" id="OpenSpeedTest-UI" data="/assets/images/app.svg" type="image/svg+xml"></object>`` 


Therefore, the JS in assets/js/app-2.5.4.min.js fails and the page isn't loaded any further.


Please check the JS for any absolute paths, as the up-/downloading paths aren't correct either.

app-2.5.4.min.js line 48:   /upload /downloading

app-2.5.4.js line 671:   /upload /downloading

darkmode.js line 4: href="/assets/css/darkmode.css"

**Comment by openspeedtest** [comment]
@klepptor hmm, Try now. Delete local image before run.

**Comment by klepptor** [comment]
@openspeedtest Yeah, now it's working fine in my environment!

OpenSpeedTest docker in a subdir served by a reverse proxy/load balancer

Thx a lot for your amazing work!

**Comment by openspeedtest** [comment]
Done! Test and look at browser console. Make sure everything working fine. Thanks
Warning! If you run it behind https://github.com/openspeedtest/Speed-Test/issues/4#issuecomment-1229157193 you should increase post body content length to 35 Megabytes or more.
