### ISSUE TITLE
any way to force to test agains localhost

### ISSUE THREAD

**Issue by mckaygerhard** [openspeedtest/Speed-Test#37]
maybe do nto have such sense.. but i want to visit from any ip and the test will be agains the loopback ip

**Comment by openspeedtest** [comment]
Install OpenSpeedTest-Server on the machine. Then visit localhost:3000 , if you run it on Android/iOS device use split screen. Otherwise it will kill the app in the background. If you need to find full potential of the device. You need MacOS or Linux, with Nginx. Then use Google Chrome or Safari.

**Comment by mckaygerhard** [comment]
yes noted that over firefox do not got full speed.. and of course i dont use crappy windo..  ok i guess i dont explain myselft enough:

when I do the test, obviously the packets are sent between the client and the server, there is a way that this is sent on the same server and the speed is reported from the server...

ok i believe that openspeedtest is totally client side and this issue would totally change the meaning right? umm i will close this issue .. sorry for noise about it
