### ISSUE TITLE
when more clients perform the test, the bandwidth result is shared! so its not so usefully

### ISSUE THREAD

**Issue by mckaygerhard** [openspeedtest/Speed-Test#38]
i installed all settings as defaults with 1000Mbps interface..

i try to perform two test and results are divided in clients.. that is not the desired result!

**the bandwidth is distributed between the two clients, I know that it is logical if they both go against the same server**... how can I make them both suck the same 1000MBps... I know that this is with the webserver... **how can be done in lighttp apart from nginx too?**

in desktop perform the test at same time as in laptop.. check the video:

https://user-images.githubusercontent.com/1571724/191628384-045e6109-045b-4d2a-9339-2f5aafbf14e5.mp4

**Comment by openspeedtest** [comment]
If you have 1gbps NIC the maximum download and upload capacity of your server will be 1 gbps. If you try to test from multiple devices with 1gbps total bandwid, it will be shared between both devices. If you like to saturate both devices you need to upgrade the server NIC to 10Gbps.

**Comment by mckaygerhard** [comment]
> If you have 1gbps NIC the maximum download and upload capacity of your server will be 1 gbps. If you try to test from multiple devices with 1gbps total bandwid, it will be shared between both devices. If you like to saturate both devices you need to upgrade the server NIC to 10Gbps.

ok but tell me why the okla own hosted server will give total for both.. (until demo expired of course, and started to floot to me with premium offers)

**Comment by openspeedtest** [comment]
Client download speed = server upload speed.
Client upload speed = server upload speed. 
If client and server have 1 Gbps NIC, it can download and upload at 1Gbps. If you connect 2 equally capable clients with 1Gbps Nic to a 1Gbps NiC server you will see 500Mbps (1G/2).. you will not get more that 1Gbps on both devices at the same time. Finish the test on one device, then run test on another device. Now both devices will show 1Gbps.

**Comment by mckaygerhard** [comment]
> Finish the test on one device, then run test on another device. Now both devices will show 1Gbps.

err the okla service with same 1G show 1G .. i guess that: they send in small packets and use same principies of the cpu's that only can process one instruction but so so faster that simulates much more instructions at same time.. do you got it? the idea?

**Comment by openspeedtest** [comment]
So you are telling that your server speed was more than 1 gbps when you tested? I don't know how that works.

**Comment by mckaygerhard** [comment]
> So you are telling that your server speed was more than 1 gbps when you tested? I don't know how that works.

no, I am saying that when Okla deployed the server it said the same speed for both clients, but i am losing the hope cos that you said makes sense and its pretty logic
