### ISSUE TITLE
any way to get ip test and show on ui

### ISSUE THREAD

**Issue by mckaygerhard** [openspeedtest/Speed-Test#40]
any way to get ip test and show on ui? 

the srever ip can get optained from the html index page as i can see in the code.. but seems rest are iyected via javascript

**Comment by openspeedtest** [comment]
For that you need to use PHP or an external ip api.

**Comment by mckaygerhard** [comment]
the client ip i can see that the internal javascript already get it, external ip can be set using the server flags.. 

any way to parse a extra input parameter?

**Comment by openspeedtest** [comment]
I don't understand exactly what you are trying to do.

**Comment by mckaygerhard** [comment]
by example that the user put their name and i stored into the database fromt he page test using an input field

**Comment by openspeedtest** [comment]
No, we don't have an option like that. Because we don't have any text input in this application.

**Comment by mckaygerhard** [comment]
ajah, any way to do that?

**Comment by mckaygerhard** [comment]
sad to read that.. i want something lik this https://github.com/librespeed/speedtest/issues/370 the parameter "extradata" its the desired one.. but well i will realy on librespeed until this project get better flexibility features
