### ISSUE TITLE
 Wont Start

### ISSUE THREAD

**Issue by SGC1990** [openspeedtest/Speed-Test#41]
Can not get the docker contactor to start. Here is a copy of what the log in showing, I do have ssl configured.

[github-openspeedtest.pdf](https://github.com/openspeedtest/Speed-Test/files/9741923/github-openspeedtest.pdf)

**Comment by openspeedtest** [comment]
Invalid pdf

**Comment by SGC1990** [comment]
github dont like the pdf export. here is what is in the pdf.

2022/10/09 16:58:01 [notice] 1#1: start worker process 59
2022/10/09 16:58:01 [notice] 1#1: start worker process 58
2022/10/09 16:58:01 [notice] 1#1: start worker process 57
2022/10/09 16:58:01 [notice] 1#1: start worker process 56
2022/10/09 16:58:01 [notice] 1#1: start worker process 55
2022/10/09 16:58:01 [notice] 1#1: start worker process 54
2022/10/09 16:58:01 [notice] 1#1: start worker process 53
2022/10/09 16:58:01 [notice] 1#1: start worker process 52
2022/10/09 16:58:01 [notice] 1#1: start worker process 51
2022/10/09 16:58:01 [notice] 1#1: start worker process 50
2022/10/09 16:58:01 [notice] 1#1: start worker process 49
2022/10/09 16:58:01 [notice] 1#1: start worker process 48
2022/10/09 16:58:01 [notice] 1#1: start worker process 47
2022/10/09 16:58:01 [notice] 1#1: start worker process 46
2022/10/09 16:58:01 [notice] 1#1: start worker process 45
2022/10/09 16:58:01 [notice] 1#1: start worker process 44
2022/10/09 16:58:01 [notice] 1#1: start worker processes
2022/10/09 16:58:01 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/10/09 16:58:01 [notice] 1#1: OS: Linux 4.4.180+
2022/10/09 16:58:01 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
2022/10/09 16:58:01 [notice] 1#1: nginx/1.22.0
2022/10/09 16:58:01 [notice] 1#1: using the "epoll" event method
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

**Comment by openspeedtest** [comment]
Tested this on my mac, I created a folder 'docker' on my desktop
Inside 'docker' folder on the desktop nginx.crt and nginx.key (It is a self signed certificate)
you can replace it with your own key and crt.

then  run the following command 

`sudo docker run -v /Users/vishnu/Desktop/docker/:/etc/ssl/ --restart=unless-stopped --name openspeedtest -d -p 3000:3000 -p 3001:3001 openspeedtest/latest`

Replace '/Users/vishnu/Desktop/docker/ ' with your own folder path.
