### ISSUE TITLE
Change Port while using macvlan

### ISSUE THREAD

**Issue by mcdoubleyou** [openspeedtest/Speed-Test#42]
Hello,

I use my Docker with macvlan and when I change Settings in Portainer zu 80:3000 and 443:3001 nothing changed.
Anyway to change the Port the container listens on?

Thanks mcdy!

**Comment by openspeedtest** [comment]
you can edit https://github.com/openspeedtest/Nginx-Configuration and use bind mount https://docs.docker.com/storage/bind-mounts/
or create your own docker image
