### ISSUE TITLE
Jitter time always shows zero, and request for option of number of decimal places for Jitter and Latency

### ISSUE THREAD

**Issue by eehan** [openspeedtest/Speed-Test#45]
Hi I have noticed that the jitter value always shows as zero.  This is over an Internet connection with lots of Jitter.  Other speed test websites show high amounts of jitter.  I figure that there is an issue with it.
Also, is it possible to put in an option within index.html for configuring the number of displayed digits after the decimal place for Latency between 0 and 2 digits, and the same for the Jitter?

**Comment by openspeedtest** [comment]
Zero Jitter = Very good connection. 

If you get ping 7ms two times, than means 7-7=0 ms jitter

Jitter shows the stability of your connection, if you get 7 and 6.9 ms ping , jitter will be 0.1. we will report 0.1 as jiitter. If you can add artificial jitter to a connection, you can test this.  If you run this on a congested 4G or 3G connection you will see jitter values more than 5ms most of the time.

**Comment by eehan** [comment]
Thanks for your response.  I really don't think you have taken the time to understand my issue above.  I know what jitter is *sigh*
The problem is that using your software the JITTER ALWAYS SHOWS ZERO.  ALWAYS.

Even over links of high jitter with a high variance in ping times such as 4G.  IT ALWAYS SHOWS ZERO.  ALWAYS.

Hence I've raised the issue.
![jitter](https://user-images.githubusercontent.com/6690674/197265375-80bae2d8-e189-494b-b172-5f271df08cbf.PNG)

**Comment by eehan** [comment]
FYI I have increased the number of pings a the start of the test to 100.

**Comment by openspeedtest** [comment]
Increased sample is not a problem, i think it's always comparing the difference between the last ping value, so if you got 20ms ping two times in a test, 20-20 = 0 will be the least value. That will be reported. Anyway I will check this behaviour soon and post an update.

**Comment by eehan** [comment]
> so if you got 20ms ping two times in a test, 20-20 = 0 will be the least value. That will be reported.

It would be more useful to see the jitter value calculated as an average jitter over the number of pings in the initial ping test.  So for example if number of pings = 100, then the jitter between each consecutive packet is summed up and then divided by 99 at the end to produce the one average jitter value.

**Comment by openspeedtest** [comment]
Yes, we need to find a better way to report jitter. 
https://user-images.githubusercontent.com/51720450/197316187-b1ea8356-c167-4a1b-9b8d-db872786c67f.mp4
as you can see from the video, when we send 100 pings, the high jitter is over 2400ms and low is 0, an average between both will be highly inaccurate. maybe we need calculate SMA or something else.

**Comment by openspeedtest** [comment]
(20 Samples) [0, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.4, 0.5, 0.5, 0.7, 0.7, 1.3, 1.4, 2, 4.5, 5.8, 8.3, 8.9, 12.9]
(10 samples) [0, 0.1, 0.1, 0.2, 0.2, 0.2, 0.3, 0.4, 0.5, 0.5]   [50% of samples with least values]
sum/length of 10 sample 
2.5/10=0.25

![Screenshot 2022-11-18 at 1 25 58 PM](https://user-images.githubusercontent.com/51720450/202650337-1f0dde52-a5e5-4f86-ad43-74d0cbadb934.png)

**Comment by eehan** [comment]
As far as I am concerned the idea of the average jitter measurement is to average across all values, not a percentile of.  But if you wanted to include a percentile variable in the code that the user can change to choose the x% least jitter values in the calculation, that's probably not a bad idea.  Although if you ask me, it is an unnecessary complication and calculation for your code.
I figured the only delay variation values that should be excluded are when there is a missed ping response, for example.  Let's say you are half way through the pings and one drops, in this case you would need to exclude two jitter values from the calculation and reduce the total samples by two.  But this means each ping has to be identifiable with a sequence number so you know which packet was dropped.  I guess that does start to complicate things since you are probably not identifying packet sequence numbers, or are you?

**Comment by openspeedtest** [comment]
We cannot identify a drop, because TCP will hide that info. But we can track errors, but it's useless. 
I can provide a variable in index.html where you can adjust the sample size. 

var jitterFinalSample = 0.5; // 1 = 100%, 0.5 = 50%, 0.1 = 10% like that

**Comment by eehan** [comment]
OK that makes it difficult.  Jitter sample size percentage is a fair compromise then.  Thanks for your work on this.

**Comment by openspeedtest** [comment]
OpenSpeedTest updated to 2.5.3
- improved jitter reporting.
- run a speed test by hitting Enter Key from Keyboard
