### ISSUE TITLE
Problem with startup trying to do IPv6

### ISSUE THREAD

**Issue by dlhace** [openspeedtest/Speed-Test#47]
So I have run this in a docker on a server and it runs fine, but I am trying to run this in a container runner (cloud foundry)

on docker image latest
I have looked at the scripts and based on the logs IPv6 shouldn't be configured, but then the nginx server gives and IPv6 error,

Is the Docker build file(s) available in version control so I can modify it to just do basic IPv4?

LOGS
   2022-10-25T16:33:37.72-0600 [APP/PROC/WEB/0] OUT **10-listen-on-ipv6-by-default.sh: info: ipv6 not available**
   2022-10-25T16:33:37.73-0600 [APP/PROC/WEB/0] OUT /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
   2022-10-25T16:33:37.73-0600 [APP/PROC/WEB/0] OUT /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
   2022-10-25T16:33:37.73-0600 [APP/PROC/WEB/0] OUT /docker-entrypoint.sh: Configuration complete; ready for start up
   2022-10-25T16:33:37.75-0600 [APP/PROC/WEB/0] ERR 2022/10/25 22:33:37 [emerg] 8#8: socket() [::]:3000 failed (97: Address family not supported by protocol)
   2022-10-25T16:33:37.75-0600 [APP/PROC/WEB/0] ERR nginx: [emerg] socket() **[::]:3000 failed** (97: Address family not supported by protocol)

**Comment by openspeedtest** [comment]
Added this few days ago. https://github.com/openspeedtest/Nginx-Configuration/pull/2
Some people need IPV6, you can edit the Nginx configuration and disable IPV6.

**Comment by dlhace** [comment]
"Is the Docker build file(s) available in version control so I can modify it to just do basic IPv4?"  By this I mean can I get a copy of your build stuff to build my own without the IPV6.  I don't to modify your stuff.  Ie do a git fork over to my own git repository to do some custom modifications for myself.

**Comment by RoboMagus** [comment]
Running into the same issue as well.

> Added this few days ago. [openspeedtest/Nginx-Configuration#2](https://github.com/openspeedtest/Nginx-Configuration/pull/2) Some people need IPV6, you can edit the Nginx configuration and disable IPV6.

Would be more convenient if there were an ENV variable we could add in compose to indicate if the IPv6 should be enabled / disabled.

**Comment by openspeedtest** [comment]
@dlhace @RoboMagus Please check this https://github.com/openspeedtest/Docker-Image 
Please send a pull request if you can improve this docker image.

**Comment by RoboMagus** [comment]
Looking at the base image you're using there's already a file that checks at startup for the availability of an IPv6 interface: `/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh`. However it looks at the default.conf file.
I would propose modifying that script to work on the openspeedtest config file, and the ports it uses.

However I'm currently not able to modify and more importantly, test these proposed changes. Perhaps in a couple of weeks I might be able to open up a PR.

**Comment by openspeedtest** [comment]
You can modify OpenSpeedTest-Server.conf and mount the file to the container. 
to disable ipv6 remove or comment the following lines.  
        listen [::]:3000;
        listen [::]:3001 ssl;

**Comment by openspeedtest** [comment]
@dlhace @RoboMagus 
Image Updated with Fix https://github.com/openspeedtest/Docker-Image/pull/2
