### ISSUE TITLE
Results returning only local speeds?

### ISSUE THREAD

**Issue by droidus** [openspeedtest/Speed-Test#48]
I ran my self-hosted instance and it seems to be reporting 1 GB down and 570mbps up.  I know my speeds are only 300/300mbps.  I believe it is just measuring my local speeds.  I added ?Host= to point to the openspeedtest.com IP, and I get the same results.  What do I need to do to measure actual Internet speeds?

**Comment by openspeedtest** [comment]
If you need to run an internet speed test use Openspeedtest home Page. 
If you host your own server in the cloud with right Cross-Origin Resource Sharing (CORS) permission, you can pass it using "Host" keyword. Soon i am planning to provide a list of publically available servers, i think people can use it like the way you mentioned in the near future.

**Comment by leandrop98** [comment]
@openspeedtest Did you get the list of publicly available servers? I am running Openspeedtest on localhost since want to make some modifications but when I try different servers I get the following error:

```
Access to XMLHttpRequest at 'https://openspeedtest.com/upload?n=0.040863307044817665' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
What servers should I be using?
