### ISSUE TITLE
[Feature Request] Support for reverse proxy in subfolders

### ISSUE THREAD

**Issue by gritstub** [openspeedtest/Speed-Test#5]
I would like to put this behind my swag reverse proxy, using a subfolder, like:

http://mydomain.com/myopenspeedtest/

It needs to support a base url, so it works behind a directory

**Comment by openspeedtest** [comment]
Services behind reverse proxy server will not or not need to know your domain name or url structure. 
It doesn't matter where you put the application. 
You are using docker? 
I am missing something. ,🤔

Please post more details.. 
Steps to reproduce this issue and expected chage / fix 
Thanks

**Comment by gritstub** [comment]
I am running in a Docker, and am using swag (nginx) to create a reverse proxy via subfolder.

eg: http://mydomain.com/myopenspeedtest/

My swag nginx looks like
```
location /myopenspeedtest/ {
  rewrite ^/myopenspeedtest(.*)$ $1 break;
  proxy_pass http://openspeedtest:3000;
}
```

Now the main page can open, however, the openspeedtest doesn't like being in a folder.

The links to "uploader" and "downloader" are absolute paths to the root.  Please change them to be relative.
```
        { "hostName": "/upload" }
```

and

```
m[a].open("GET",comopenspeedtestcdn+"/downloading?n=
```

You can just change it to "./" instead of "/"

**Comment by openspeedtest** [comment]
open index.html in a text editor and modify the following 
under script tag.

// This is for ping add more URL for more ping samples and more precise result 
 var comopenspeedtesturl = {
      "serverList": [
        { "hostName": "//yourdomain.com/subfolder/downloading" },
        { "hostName": "//yourdomain.com/subfolder/downloading" },
        { "hostName": "//yourdomain.com/subfolder/downloading" },
        { "hostName": "//yourdomain.com/subfolder/downloading" },
        { "hostName": "//yourdomain.com/subfolder/downloading" }
      ]
    };
    //
// this is for upload 
    var comopenspeedtestuurl = {
      "serverList": [
        { "hostName": "//yourdomain.com/subfolder/upload" }

      ]
    };
//  download file url 
    var comopenspeedtestcdn = "//yourdomain.com/subfolder/downloading";


I am developing a new version so this setup will change in future. But it will be much easier to add custom path or list of hostnames. 

Now mount modified index.html to your docker container. 

path will be /usr/share/nginx/html/index.html 

add -v in docker command / compose file

-v /PATH-TO-YOUR-HTML-MOD/**:/usr/share/nginx/html/**

**Comment by gritstub** [comment]
I've made my changes locally with `./downloading` and `./upload`, which works fine.
It's unnecessary to add the domain and path, since they reside in the same relative path.

I'm hope that you can take this into account for your next version, so that I can just use your docker without modifications.

**Comment by openspeedtest** [comment]
Done https://github.com/openspeedtest/Speed-Test/issues/32

**Comment by mikegleasonjr** [comment]
Is there an anvironment variable for the docker image to set this? Tell that we're behind a reverse proxy in a subfolder for the images to work?
