### ISSUE TITLE
Use SSL on Windows?

### ISSUE THREAD

**Issue by rtkpX** [openspeedtest/Speed-Test#50]
Apparently all tutorials are made for Linux, so, how can I start my server using a TLS certificate that's on a different folder?

Is it by starting it with a .bat file like `"openspeedtest.exe --tls-cert "path" --tls-key "path""` or something like that??

**Comment by openspeedtest** [comment]
Electron app? No. This is for desktop users. It will not support SSL and it's a GUI app, will not run Headless. 

For Headless Deployments on Windows use IIS.

check this video https://www.youtube.com/watch?v=N4WQnAfJUHY&t=6s

SSL on IIS? Check YouTube.
