### ISSUE TITLE
[Feedback] Some things that I found

### ISSUE THREAD

**Issue by AndRo-Marian** [openspeedtest/Speed-Test#53]
1. I have a Wire and a WiFi connection on the PC.
    A. http://192.168.1.100:3000 for Wire and http://192.168.1.113:3000 for WiFi
    If I try to speed test both (only one at once) the connection is not going trought router, because I get speeds over 2000 and the router can maximum of 100 on Wire and is not using Network card, Utilization is 0%, just big CPU usage.
    B. Same for 192.168.1.113 seams I can't test the PC Wire -> Router -> PC WiFi / PC Wire, going straight to PC -> Self
2. Add a way to change the mb/s to MB/s.

**Comment by openspeedtest** [comment]
I think you visited the SERVER URL from The SERVER Itself. 
Open the Server URL Shown in OpenSpeedTest-Server from a Client Device. 
Server -> Device A (Running OpenSpeedTest-Server)
Client -> Device B (Open Chrome and visit the IP address shown in Device A)

I will add this feature in the next major release.
