### ISSUE TITLE
Is it possible to run this via CLI via a router?

### ISSUE THREAD

**Issue by benisai** [openspeedtest/Speed-Test#54]
Hello, would it be possible to install this on a router (openwrt) and run it via CLI to get an output??

**Comment by openspeedtest** [comment]
All we need is Nginx, if you have space (30mb) and processes power you can. 
No, we don't have a CLI-Client (planned but not started working)

**Comment by grigio** [comment]
+1 it would be nice to call it via cli and cronjob

**Comment by openspeedtest** [comment]
@grigio Yes, it was planned for this December, but got some unexpected works. I will come back to this in February.

**Comment by benisai** [comment]
Awesome. Thanks for letting me know. 👍
