### ISSUE TITLE
Show the result self-hosted too

### ISSUE THREAD

**Issue by AuthorShin** [openspeedtest/Speed-Test#55]
I think it's not a good practice to have the result shown on your website ([opensppedtest](https://openspeedtest.com/)) instead I believe it should be shown on the same server that is hosting the speed test, because there might be an environment where there is no internet to open your website or simply someone doesn't want to do it every time they want to see the test result.

Same thing for custom URL parameters, I think there should be a link to a guide on the test page as well which is self-hosted (a short version with less description (maybe just a popup box or tooltip))

**Comment by openspeedtest** [comment]
That is an important feature. Email the result page to an IT Professional for troubleshooting connectivity issues.
So they can see the speed, jitter & ping along with transferred data. So you can find and fix issues by analyzing those values on the result page. Even if you are offline, you can copy the link and view it online later.
#29

Most people don't need or maintain a database server and need a way to share results. that is why this exists.


I am planning to write a PDF or create Page with simple instructions for parameter support. 
Like stress test etc.

**Comment by openspeedtest** [comment]
![187906953-2d5f64d9-4006-4e6b-b873-14e1c0d604e4](https://user-images.githubusercontent.com/51720450/207201570-bca50c27-3089-4f0c-92ac-079e39489d58.png)
No internet or behind a firewall? 
You can do this.

**Comment by AuthorShin** [comment]
I'm not talking about showing it on the same page I'm talking about having another page to show the results but locally, like this:
http://192.168.1.1:3000/results/873t4r87

**Comment by AuthorShin** [comment]
Plus when I'm working in an environment where there is no internet I want to see the detailed results right at that moment copy/pasting a link wouldn't do me any good.

**Comment by openspeedtest** [comment]
just read the values 
eg : https://openspeedtest.com/results/show.php?&d=86.418&u=17.183&p=267.7&j=0.2&dd=116.740&ud=27.969&ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/108.0.0.0%20Safari/537.36

https://openspeedtest.com/results/show.php?
&d=86.418 <-- Download 
&u=17.183 <-- Upload
&p=267.7 <-- ping
&j=0.2 <-- Jitter
&dd=116.740 <-- Downloaded data during test
&ud=27.969 <-- Uploaded data during test
&ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/108.0.0.0%20Safari/537.36 <-- User Agent

**Comment by AuthorShin** [comment]
> Most people don't need or maintain a database server and need a way to share results. that is why this exists.

Why database? You don't need to add a database for it like you don't have for the way it is right now that shows on your website, there is only a need for a page on the same server to show the generated results.

http://192.168.1.1:3000/results/show.php?&d=1248.853&u=543.844&p=10&j=2.6&dd=1892.560&ud=690.000&ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64;%20rv:107.0)%20Gecko/20100101%20Firefox/107.0

This will be the output link for that when you click on it, it will show you the result.

**Comment by AuthorShin** [comment]
> just read the values eg : https://openspeedtest.com/results/show.php?&d=86.418&u=17.183&p=267.7&j=0.2&dd=116.740&ud=27.969&ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/108.0.0.0%20Safari/537.36
> 
> https://openspeedtest.com/results/show.php? &d=86.418 <-- Download &u=17.183 <-- Upload &p=267.7 <-- ping &j=0.2 <-- Jitter &dd=116.740 <-- Downloaded data during test &ud=27.969 <-- Uploaded data during test &ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/108.0.0.0%20Safari/537.36 <-- User Agent

Why not add a page for showing this values as readable results?

**Comment by openspeedtest** [comment]
Results are already showing. As I said, Extra info that is irrelevant for most users but helpful for troubleshooting is in the URL. If you need, you can just read the values from the URL. 

Just static webpage + Nginx, No PHP or Node.js involved.

**Comment by AuthorShin** [comment]
Okay I'll do it myself.
