### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by xemulat** [openspeedtest/Speed-Test#57]
`OpeSpeedtest.com`  instead of `OpenSpeedtest.com`

Site: https://openspeedtest.com/selfhosted-speedtest

![image](https://user-images.githubusercontent.com/98595166/208163647-ca647da7-eab3-428a-b61d-fcac229070e9.png)

**Comment by openspeedtest** [comment]
I fixed the typo. Thanks for reporting! .
![Screenshot 2022-12-19 at 5 10 20 PM](https://user-images.githubusercontent.com/51720450/208418088-b30ee22c-33bb-4c17-ac65-47d9fc8e640b.png)
