### ISSUE TITLE
Add this app to fdroid

### ISSUE THREAD

**Issue by CodeCubeNeo** [openspeedtest/Speed-Test#59]

**Comment by openspeedtest** [comment]
Why?

**Comment by openspeedtest** [comment]
Already in https://play.google.com/store/apps/details?id=com.openspeedtest.server
If your phone don't have Google Play, download the APK file. Use websites like APK mirror or pure.

**Comment by CodeCubeNeo** [comment]
Because it shows your support for open source software. If you publish it there, more people can discover it (open source fans dont check new apps on play store, but do on fdroid (or izzydroid)

**Comment by openspeedtest** [comment]
@CodeCubeNeo oh.. I got your point. It's just an Ionic app that uses iOnic webserver. I am not sure it's compatible or not. Anyway I will check those options.  Thanks.
