### ISSUE TITLE
[Feature Request] Configurable length of test

### ISSUE THREAD

**Issue by deangoldhill** [openspeedtest/Speed-Test#6]
The option to set the length of time the test will run, would be of great use.
for troubleshooting/upgrading/configuring network equipment, would be helpful to have the test run continuously so you can notice the effects instantly.

**Comment by openspeedtest** [comment]
i am working on that. It will be ready within few days.

**Comment by deangoldhill** [comment]
That's Awesome!

**Comment by openspeedtest** [comment]
updated docker image. with stress test https://twitter.com/openspeedtest/status/1490689706321154048?s=20&t=flJiw7Wb1_cQw3z0mqK1-A

**Comment by deangoldhill** [comment]
works perfectly, thanks!
