### ISSUE TITLE
How to save results to mongodb?

### ISSUE THREAD

**Issue by thangdalat** [openspeedtest/Speed-Test#60]
Please show me how to save the result to mongodb. Thank you.

**Comment by openspeedtest** [comment]
Check         https://github.com/openspeedtest/Speed-Test/blob/d8013dc6468abdd57b3ba7e438cf161487399c75/index.html#L106 

Change it to true. 
Then provide url with logic to save data. 
After each test it will make a post request. 
You can write the logic to save data to a database in any programming language.. eg php or node.js 

This is a DIY solution.

**Comment by thangdalat** [comment]
Can you do an example in node.js for me? Thank you very much.

**Comment by openspeedtest** [comment]
This is out of scope feature for this project. You need to Do it yourself or hire a Freelancer.
Check this, Very easy to do. 
https://www.geeksforgeeks.org/how-to-connect-node-js-to-a-mongodb-database/
https://www.geeksforgeeks.org/how-http-post-request-work-in-node-js/
