### ISSUE TITLE
When using docker container deployment services for testing, only one core can be invoked, resulting in lower testing speed.

### ISSUE THREAD

**Issue by qianxu2001** [openspeedtest/Speed-Test#61]
I am running the service on an armv7 device with 4 cores via docker container, but the performance of each core is low, resulting in low speed when testing, is it possible to call multiple cores to improve the performance?
![image](https://user-images.githubusercontent.com/62287903/211211159-39894ef2-99e1-4643-a202-817a5e732026.png)
![image](https://user-images.githubusercontent.com/62287903/211211160-dd6b6121-f07d-483c-9202-720fe0c27e70.png)

**Comment by openspeedtest** [comment]
@qianxu2001 
Which device?
I tested this on a Raspberry Pi Model B and got 940+ on both sides. 
Did you use the Official Docker image? 
If this is an Old Raspberry Pi Model B, you may need to OverClock it to achieve full speed. 
We are using Nginx Server. It should use all cores, but Single Core performance is Very Important. 
All [NGINX Performance Tuning](https://sysopstechnix.com/7-tips-for-nginx-performance-tuning/) tips can be used or tested. 
When I tested my Raspberry Pi Model B last time, Core 1 was utilised on average 60 to 70%. That is not unusual. 

https://user-images.githubusercontent.com/51720450/211239356-212edd53-f182-4d20-b056-7b0abe6a9655.mp4

**Comment by qianxu2001** [comment]
> 

My device is powered by an Amlogic S805 processor, which I cannot overclock, and I am trying Nginx performance tuning.
I am using the official Docker image and just tried to modify /etc/nginx/nginx.conf inside the container, but vi prompts that 'nginx.conf' is read only.

**Comment by openspeedtest** [comment]
@qianxu2001 Here is the [Docker Image Project](https://github.com/openspeedtest/Docker-Image) Build and Test using local image.

**Comment by qianxu2001** [comment]
> @qianxu2001 Here is the [Docker Image Project](https://github.com/openspeedtest/Docker-Image) Build and Test using local image.

I modified the configuration, using about 1.3 cores, the test speed is close to 800Mbps, the effect is not obvious, I will replace the device to deploy the service in the near future, thank you for your answer.

**Comment by openspeedtest** [comment]
If you find the modified configuration useful for everyone, let me know. We can modify the docker image. 
Thank you. @qianxu2001
