### ISSUE TITLE
License is confusing

### ISSUE THREAD

**Issue by cgi-psaunders** [openspeedtest/Speed-Test#63]
Hello,

I notice that your project is caled "Open" Speed Test and you have a file at the top of the project (`License.md`) which states:

> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software _without restriction_, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions

(emphasis mine)
However, in the actual source code (for example https://github.com/openspeedtest/Speed-Test/blob/main/index.html#L26) there is the following statement:

> ©CopyRight 2013-2023 by OpenSpeedTest.COM. All Rights Reserved.

Under the MIT license you are waiving all rights, but with this line you are reserving all rights.

Please could you clarify whether people have the rights stated under the MIT License or not?

**Comment by openspeedtest** [comment]
Yes, People have all rights stated under the MIT License.
[ It's FOSS. You can do whatever you see fit.](https://github.com/openspeedtest/Speed-Test/blob/main/index.html#L145)
