### ISSUE TITLE
Error : OpenSpeedTestdb is not defined

### ISSUE THREAD

**Issue by AlexDesign-Fr** [openspeedtest/Speed-Test#65]
Hi,
When I try to record my request in a database, I've got the error (not sure this is a consequence):
`OpenSpeedTestdb  is not defined`
In index.html I've set 
`var saveData = true;
var saveDataURL = "http://MyCorrectNameServer:4500/save?data=";`
Any Idea where this error came from ?

Best regards
Alex.

**Comment by openspeedtest** [comment]
add
var OpenSpeedTestdb;
In Index.html (above saveData)
and see it's working as expected or not.

**Comment by AlexDesign-Fr** [comment]
Nice.
It's works, thanks.

**Comment by satsis** [comment]
// Save Data to a Database
        var saveData = true;
        var saveDataURL = "http://hd.zp.ua/save.php?data=";

OpenSpeedTest.com **V2.5.4** Loaded!
**Uncaught ReferenceError: OpenSpeedTestdb is not defined**
