### ISSUE TITLE
AppImage local up/down different?

### ISSUE THREAD

**Issue by axi92** [openspeedtest/Speed-Test#66]
I started the appimage local to see if the different speeds on our local network from up to download persist.

Should down and upload local be the same?
![image](https://user-images.githubusercontent.com/1394837/214524975-740d4b92-2b74-4153-a8b7-553f25bde6b5.png)

**Comment by openspeedtest** [comment]
If you are testing this on a 10G Wired connection, should see 9400+ for up and down.

I think you are using FireFox. 

I don't know the exact reason. Firefox is slow on all platforms.
https://bugzilla.mozilla.org/show_bug.cgi?id=1779764
SPX labs testing Firefox and Safari 
https://www.youtube.com/watch?v=RmUt-xPJuWc&t=130s

Firefox is not recommended for Stress Tests above 10 Minutes or Speeds above 2.5Gbps. Browser extensions can negatively affect Latency reports and Overall performance. Try to run a speed test in incognito mode or from a browser 
without extensions.

Chrome, Edge, Safari, Opera, Brave etc., can run 10Gbps+ & Run continuous speed tests for hours or even days. Incognito Mode or a Browser without extensions is recommended for more accurate results.

For 2.5Gbps+

Edge is better if you use Windows.

Safari is better if you use Mac.

Chrome is better if you use Linux.

https://twitter.com/openspeedtest/status/1606172917519503361


https://user-images.githubusercontent.com/51720450/214527045-2cfb45f5-2b53-4be4-93e4-7bee4d041031.mp4

And, If you know how to run Docker or Nginx, that will perform better than Electron Apps for Desktop on Linux Platform.

**Comment by axi92** [comment]
I was testing on my local machine with my local firefox thats correct.
I have this issue that I get inside the company network D: 211 and U: 2
![image](https://user-images.githubusercontent.com/1394837/214820458-feb5e4be-c1f0-492e-b967-950d8e5805bc.png)

But when i upload a 1GB file via scp I get 30MB/s
```1GB.bin                                                                                                                         100% 1000MB  30.7MB/s   00:32 ```

As I am writing this, we use caddyserver for the reverse proxy.

I tried this from that issue #44 did I miss something?
```
	reverse_proxy http://10.64.192.147:4000 {
		buffer_requests
		buffer_responses
		flush_interval -1
		max_buffer_size 35MiB
	}
```

In the caddy debug logs it canceled the stream on upload:
```
Jan 26 12:21:36 sfw-proxy caddy[2366879]: {"level":"error","ts":1674732096.1729233,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream 256 canceled with error code 268"}
Jan 26 12:21:36 sfw-proxy caddy[2366879]: {"level":"error","ts":1674732096.1731646,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream 248 canceled with error code 268"}
Jan 26 12:21:36 sfw-proxy caddy[2366879]: {"level":"error","ts":1674732096.1778808,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream 252 canceled with error code 268"}
Jan 26 12:21:36 sfw-proxy caddy[2366879]: {"level":"error","ts":1674732096.1855493,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream 260 canceled with error code 268"}
Jan 26 12:21:36 sfw-proxy caddy[2366879]: {"level":"error","ts":1674732096.1948066,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream 244 canceled with error code 268"}
Jan 26 12:21:36 sfw-proxy caddy[2366879]: {"level":"error","ts":1674732096.2100446,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"stream 264 canceled with error code 268"}
```

**Comment by openspeedtest** [comment]
interesting! 
See https://github.com/openspeedtest/Speed-Test/issues/67 
I got it working on Public Cloud and my local 10GbE test systems. 
Tested 10GbE with Caddy -> https://www.youtube.com/watch?v=0pD8fen2nNg
Check Caddy Version, If outdated update it.
