### ISSUE TITLE
Upload tests timeout with caddy server

### ISSUE THREAD

**Issue by Mikle-Bond** [openspeedtest/Speed-Test#67]
Hello. 

I was trying to use caddy as reverse proxy in front of OST. The download tests work fine, but uploads behave weirdly.

![2023-01-24 14_08_30-Speed Test by OpenSpeedTest com](https://user-images.githubusercontent.com/5671588/214598251-225177c1-a4f0-4032-8b8f-b2eb0f1e716c.png)

It seems, that the first few packages are sent from browser to server, and the rest of transmission is not taken into account. Or fails. Or timeouts. I don't even know anymore. As graph shows overall average, there are 5-6 spikes at the beginning when xhr-connections are initiated, and then it approaches 0 as more 0-speed measurements are taken.

I have tried every trick I could find online:
 - setting `reverse_proxy > transport > compression off`
 - limiting connections to HTTP 1.1
   - via `reverse_proxy > transport > versions 1.1`
   - via `tls > alpn http/1.1`
 - increasing buffer size
   - via `reverse_proxy > max_buffer_size 100MiB`
   - via `request_body > max_size 100MiB`
   - via `reverse_proxy > transport > max_response_header 100MiB` (just to be sure)
 - forcing buffering with `reverse_proxy > buffer_requests` and/or `reverse_proxy > buffer_responses`
 - disabling buffering with `reverse_proxy > flush_interval -1`
 - increasing timeouts with  `reverse_proxy > transport > dial_timeout 10m`

I've tried all of the above in different combinations, and yet, upload won't work.

I know this is caddy-specific issue, but in [another issue](https://github.com/openspeedtest/Speed-Test/issues/22#issuecomment-1228334526) you've mentioned that you're interested in making caddy work with OST. The configs at #44 didn't work for me, and the author there didn't confirm them to work either.

I have also tried to serve files directly via caddy's built-in `file_server`, and I tried to mimic the Nginx's configs taken from [here](https://github.com/openspeedtest/Docker-Image/blob/main/files/OpenSpeedTest-Server.conf), to no avail either. Exact same results.

Interestingly, when I proxied OST via caddy-l4 instance, without terminating TLS, everything worked fine. 

I hope you will have a better luck configuring caddy. If you know anything else I can try, please let me know.

**Comment by openspeedtest** [comment]
@Mikle-Bond 
Delete everything and try
````
         reverse_proxy http://localhost:3000 {
         buffer_requests
         buffer_responses
        }
````

**Comment by openspeedtest** [comment]
````
         reverse_proxy http://localhost:3000 {
         buffer_requests
         buffer_responses
         flush_interval -1
         max_buffer_size 35MiB
        }
````
Adding [flush_interval](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#flush_interval) may help reduce memory usage. 
[max_buffer_size](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#max_buffer_size) I didn't see a difference when tested with and without max buffer. Still, I think it's better to specify a number.

**Comment by openspeedtest** [comment]
Tested 10GbE with Caddy -> https://www.youtube.com/watch?v=0pD8fen2nNg
It was also tested with SSL on a Public Cloud.
I think it's working fine.

**Comment by bt90** [comment]
@openspeedtest out of curiosity, did you check HTTP/3 ?

**Comment by openspeedtest** [comment]
@bt90 Yes https://github.com/openspeedtest/Speed-Test/issues/52#issuecomment-1404451368 
It was tested using Caddy.
HTTP2 & 3 have Not yet been added to the Docker image.
I need to run more tests. 
HTTP3 Nginx still in beta?.

**Comment by bt90** [comment]
Caddy enables HTTP/3 by default. That's why i'm asking. Note that you need an explicit binding for 443/udp if you're using their docker container.

As for nginx, it's still in development.

**Comment by openspeedtest** [comment]
Oh, I Installed it without using Docker https://caddyserver.com/docs/install#debian-ubuntu-raspbian

**Comment by bt90** [comment]
That should work. Is a firewall involved?

**Comment by openspeedtest** [comment]
@bt90 
No, It was a Direct connection between M1 MacMini and My VMware ESXi Server.
Tested on a Public Cloud, and HTTP3 using Caddy worked fine.

**Comment by bt90** [comment]
Are you sure? I don't think that their HTTP/3 implementation is able to saturate a 10G link (yet).

https://github.com/quic-go/quic-go/issues/3670

**Comment by openspeedtest** [comment]
@bt90 I thought you asked about HTTP3 handshake https://youtu.be/_QQX0Ezpq8U?t=1235 over firewall.
I tested Caddy with Internal TSL on localhost., it is not touching 10Gbps. 

_with TSL - H3 7000+ Download and 980+ Upload
without TSL H 1.1 9400+ Download and 9400+ Upload_

I think this was because of the consumer-grade hardware. I used.
I tested NPM & Traefik Proxy on the same device using HTTP1/2 last year using TSL.
Found similar performance degradation when using behind a reverse proxy.
Ether this is because of the hardware I used or reverse proxy limitation by Design.

**Comment by headcrushed** [comment]
To people who end up here because of unrealistic upload speeds. 
Instead of 
```
         reverse_proxy http://localhost:3000 {
         buffer_requests
         buffer_responses
         flush_interval -1
         max_buffer_size 35MiB
        }
```

use this
```
         reverse_proxy http://localhost:3000 {
         request_buffers 35MiB
         response_buffers 35MiB
         flush_interval -1
        }
```
It seems "buffer_requests", "buffer_responses" and "max_buffer_size" are deprecated.

**Comment by d-Rickyy-b** [comment]
It seems like you also need to disable http/3 with caddy in order to get full throughput. Sadly this can only be done on the server level and not per subdomain.

Add this at the top of your Caddyfile to receive proper results.
```
{
    servers {
        protocols h1 h2
    }
}
```

**Comment by bt90** [comment]
I can easily saturate a 2.5Gps link with caddys http3.

**Comment by d-Rickyy-b** [comment]
> I can easily saturate a 2.5Gps link with caddys http3.

That's weird. When using caddy v2.10.2, max download speed I can get is between 26-50 Mbps on a 1 Gbps link. As soon as I disable http3, download speeds reach 1 Gbps.

How did you configure caddy?

**Comment by bt90** [comment]
I'm mostly using librespeed these days. But benchmark numbers and network link utilization match when I'm running a speedtest.

**Comment by curbalman** [comment]
> It seems like you also need to disable http/3 with caddy in order to get full throughput. Sadly this can only be done on the server level and not per subdomain.
> 
> Add this at the top of your Caddyfile to receive proper results.
> 
> ```
> {
>     servers {
>         protocols h1 h2
>     }
> }
> ```

I'm seeing the same performance issue. You can try
https://github.com/caddyserver/caddy/issues/189#issuecomment-280879901
```
tls {
    alpn http/1.1
}
```
for your subdomain, or bind to a different socket and `servers <another_address> { protocols h1 }`.
