### ISSUE TITLE
Ability to disable results saving

### ISSUE THREAD

**Issue by dm1sh** [openspeedtest/Speed-Test#68]
I don't like uploading my useragent and network state to any other server. Please, add docker env to disable this functionality without editing source code.

**Comment by openspeedtest** [comment]
We are **not** uploading UserAgent and Network State to any server.
That is just **reading** the values from the URL.
**The app is not uploading or saving it to a database.** 

_That is an important feature. Email the result page to an IT Professional for troubleshooting connectivity issues.
So they can see the speed, jitter & ping along with transferred data. So you can find and fix issues by analyzing those values on the result page. Even if you are offline, you can copy the link and view it online later._ https://github.com/openspeedtest/Speed-Test/issues/29#issuecomment-1234144145
