### ISSUE TITLE
Installing in docker container on Firewalla

### ISSUE THREAD

**Issue by markywarky** [openspeedtest/Speed-Test#69]
After installing into a docker container on my [Firewalla Purple](https://firewalla.com/products/firewalla-purple) router/firewall, I can't get a response on my server (http://MY-SERVER-IP:3000). Another container running homebridge works fine.

The docker process:
```
CONTAINER ID   IMAGE                    COMMAND                  CREATED             STATUS             PORTS                                                                     NAMES
xxxxxxxxxxxx   openspeedtest/latest     "/docker-entrypoint.…"   About an hour ago   Up About an hour   0.0.0.0:3000-3001->3000-3001/tcp, :::3000-3001->3000-3001/tcp, 8080/tcp   openspeedtest

```
Docker logs for the openspeedtest container:
2023/02/06 10:14:01 [notice] 1#1: using the "epoll" event method
2023/02/06 10:14:01 [notice] 1#1: nginx/1.22.1
2023/02/06 10:14:01 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/02/06 10:14:01 [notice] 1#1: OS: Linux 4.9.241-firewalla
2023/02/06 10:14:01 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/02/06 10:14:01 [notice] 1#1: start worker processes
2023/02/06 10:14:01 [notice] 1#1: start worker process 12
2023/02/06 10:14:01 [notice] 1#1: start worker process 13
2023/02/06 10:14:01 [notice] 1#1: start worker process 14
2023/02/06 10:14:01 [notice] 1#1: start worker process 15
2023/02/06 10:14:01 [notice] 1#1: start worker process 16
2023/02/06 10:14:01 [notice] 1#1: start worker process 17

The Nginx configuration files are installed with the container, right?

Any suggestions appreciated.

**Comment by openspeedtest** [comment]
Added [routing rule for docker network](https://help.firewalla.com/hc/en-us/articles/360053441074)?

**Comment by markywarky** [comment]
Thanks for the tip, @openspeedtest!

Added routing rule for the docker network with this command:
`sudo ip route add 172.17.0.0/16 dev docker0 table lan_routable`

Got IP 172.17.0.0 from the output of this command:
`sudo docker network inspect bridge`

I don't like hardcoding the IP address of the 'bridge' network, so if anyone knows a better way of obtaining it, I'm all ears.
