### ISSUE TITLE
Verify Ownership Failing

### ISSUE THREAD

**Issue by netwalker0099** [openspeedtest/Speed-Test#71]
When attempting to verify ownership via https://openspeedtest.com/admin/verify-domain I can browse the text file at https://speedtest.ourdomain.net/Verify.txt and have verified it matches the provided key but when submitting it for activation the page fails and says Wrong Code! Verification Failed!

**Comment by openspeedtest** [comment]
No Blank space on the file? Sometimes it will generate text file with blank space at the end. I need to fix the backend. Try deleting blank space if present.

**Comment by netwalker0099** [comment]
I highlighted the entire string and I don't see any leading or trailing spaces.

**Comment by netwalker0099** [comment]
Actually, there is one.

**Comment by netwalker0099** [comment]
So, I retried the activation the space is gone, and it spun for a long time then told me the verification failed. I verified the Verify.txt again and everything looks correct.

**Comment by openspeedtest** [comment]
Please send me an email from the email I'd you used to register.  I can activate manually. support@openspeedtest.com
