### ISSUE TITLE
Impossible upload speeds for some clients

### ISSUE THREAD

**Issue by ericswpark** [openspeedtest/Speed-Test#72]
The server is on a 100 Mbps connection, yet some users report upload speeds up to several times that:

![E793B4FD-EFF4-4F37-A4A7-CE3F49495E5C](https://user-images.githubusercontent.com/13326074/227071812-29ecd2d6-4ae4-47e3-8169-f5c85597a4f6.jpeg)

As the screenshot shows, the download speed is fine and is in line with expected values.

In my current setup, the server is running in a Docker container and is reverse-proxied by Caddyserver. The config is very simple:

```
@ost host openspeedtest.example.com
handle @ost {
        reverse_proxy openspeedtest:3000
}
```

Is there anything I'm missing here?

**Comment by openspeedtest** [comment]
Check this https://github.com/openspeedtest/Speed-Test/issues/67

**Comment by ericswpark** [comment]
@openspeedtest unfortunately after testing the configuration change the user still reports an incorrect upload result:

![image](https://user-images.githubusercontent.com/13326074/227077623-28549064-1331-49a3-8052-f52eaac03f13.jpeg)

https://openspeedtest.com/results/show?&d=98.181&u=456.251&p=181&j=0.4&dd=162.284&ud=723.083&ua=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010.15;%20rv:109.0)%20Gecko/20100101%20Firefox/111.0

It's a bit less than before but still impossible. The server caps out at 100 Mbps.

On my end (iOS Safari) this is more in line with expected values:

![image](https://user-images.githubusercontent.com/13326074/227077870-70580f00-c113-4a57-8a50-b1b1524e9d22.jpeg)

https://openspeedtest.com/results/show?&d=102.098&u=16.019&p=43&j=1.0&dd=167.442&ud=19.625&ua=Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%2016_3_1%20like%20Mac%20OS%20X)%20AppleWebKit/605.1.15%20(KHTML,%20like%20Gecko)%20Version/16.3%20Mobile/15E148%20Safari/604.1

I'm wondering if this is a web browser bug. The user is using Firefox on macOS.

Also, here is the updated configuration:

{
         buffer_requests
         buffer_responses
         flush_interval -1
         max_buffer_size 35MiB
        }

**Comment by openspeedtest** [comment]
The configuration was tested on v2.6.2 h1

They released v2.6.4 which deprecated the buffer_* options and replaced it with new request_buffers and response_buffers options which take a buffer size as input. You could play around with that, try different buffer sizes and see the behaviour. Check 

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#streaming

**Comment by ericswpark** [comment]
@openspeedtest I don't quite follow – are we trying to disable buffering or enable it? Do you have any value suggestions I can try?

**Comment by openspeedtest** [comment]
Unfortunately we need Enable it. It's bad for the performance. Also the buffer size for upload should be 35 Mb. 
https://github.com/openspeedtest/Speed-Test/issues/4#issuecomment-1477726090

**Comment by ericswpark** [comment]
@openspeedtest isn't that the same as my initial configuration? I'm running Caddy v2.6.4.

**Comment by openspeedtest** [comment]
@ericswpark 
I don't have extensive experience with caddy, but I have used it both with and without TSL on my LAN. My configuration settings are identical, and I plan to try it out on a VPS tomorrow and provide an update.

**Comment by openspeedtest** [comment]
@ericswpark 
Latest Caddy uses HTTP3 by default, but I noticed slow upload speeds in Chrome and much faster upload speeds in Firefox. To address this issue, I disabled HTTP2 and HTTP3 and also enabled request buffers. After making these changes, the issue was resolved and everything is now working fine.
````
{
    servers {
        protocols h1
    }
}

speed.xyz.pro {        
                reverse_proxy localhost:3000 {
                request_buffers 35MiB
                }
}

````

**Comment by ericswpark** [comment]
@openspeedtest thank you for the reply, but unfortunately I cannot disable HTTP2/3 without disabling it for all the other services hosted by Caddy, which is not what I want. Is there a way to have OST work over HTTP2/3?

**Comment by openspeedtest** [comment]
@ericswpark I believe caddy worked well during my previous test, don't know what's changed now. Another option is to move speedtest to a dedicated subdomain using docker or Nginx.

**Comment by ericswpark** [comment]
I don't know what changed, but I can no longer reproduce this issue. Perhaps one of the updates to either OST or Caddy fixed it. Marking as solved.
