### ISSUE TITLE
Upload/downloading files source code

### ISSUE THREAD

**Issue by SergiAcrontum** [openspeedtest/Speed-Test#74]
Hello, 

I'm trying to find the source code for the upload and downloading files, are they closed source?

**Comment by openspeedtest** [comment]
https://skorks.com/2010/03/how-to-quickly-generate-a-large-file-on-the-command-line-with-linux/

**Comment by SergiAcrontum** [comment]
Alright, thank you.

I was a bit confused because both the downloading and upload files are executables, and the request included some `?n=Math.random()`, I guess that is for cache reasons.

**Comment by openspeedtest** [comment]
They are not executables. @SergiAcrontum I used dd/urandom to generate **downloading** file. **upload** is just an empty file.

**Comment by SergiAcrontum** [comment]
You are right, they are not executable in the repository.

They are in the [Dockerfile](https://github.com/openspeedtest/Docker-Image/blob/main/Dockerfile), `chmod 755`.

Thank you for the help.

**Comment by openspeedtest** [comment]
You can give 644 a try as it should work without any issues. 644 seems to be the more suitable option. However, please keep in mind that this file only contains dummy data, so it won't cause any harm.
