### ISSUE TITLE
Insane upload speeds

### ISSUE THREAD

**Issue by johncsuti** [openspeedtest/Speed-Test#76]
I have seen a few issues such as this in the past however they are using other configurations.

I have Nginx setup running directly to openspeedtest. No reverse proxy, docker, or anything.
According to openspeedtest my download speed is 16Mbps which i agree with and PfSense shows around that going out. However the upload speed shows around 3000+ Mbps while PfSense shows its not even reaching 15Mbps it tends to say around 13Mbps.

<img width="585" alt="Screen Shot 2023-04-26 at 4 58 51 AM" src="https://user-images.githubusercontent.com/22971404/234524955-f83c9714-b7f6-4b37-a0ac-199cee893b8a.png">

<img width="546" alt="Screen Shot 2023-04-26 at 4 57 17 AM" src="https://user-images.githubusercontent.com/22971404/234524517-b25982cb-2f81-4796-8ad8-e15d613ccadc.png">

Looking at the network traffic in firefox i get this.
<img width="1437" alt="Screen Shot 2023-04-26 at 4 55 34 AM" src="https://user-images.githubusercontent.com/22971404/234524122-6f65a6d0-d5fb-4dc6-859c-e9b385ad24e1.png">

If your wondering this is running from firefox using mac pro.
I have also seen it broken on firefox using ubuntu and kali linux.

Any ideas on what to try would be helpful.

**Comment by openspeedtest** [comment]
You should enable post to static file 
https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf#L43

**Comment by openspeedtest** [comment]
Also enable check post body length https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf#L42 limit should be 35 Mb or more, use this configuration and try again.

**Comment by johncsuti** [comment]
Both of those have been set it dropped the upload speed to 1700+ Mbps.

I have noticed the download file on the server has data yet the upload file has nothing. Do we need to put random garbage into the upload file?

**Comment by johncsuti** [comment]
It looks like setting https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf#L43 still doesn't allow the POST options. Looking into Nginx there isn't anything that would override this.

**Comment by openspeedtest** [comment]
I used exactly the same configuration in this docker image. https://github.com/openspeedtest/Docker-Image/tree/main/files , maybe try this docker image. Or replace your configuration with the one I posted.

**Comment by openspeedtest** [comment]
Just an empty file named ' upload ' should be there. AND YOU SHOULD USE HTTP1.1, DISABLE HTTP2/3

**Comment by openspeedtest** [comment]
If you really need http2/3 you should handle upload like this https://github.com/openspeedtest/Nginx-Configuration/blob/main/OpenSpeedTest-Server.conf#L79 but browser will use a single http connection for http2 and 6 http connection for http1. So most of the time more than one http connection is required for achieving maximum performance. So http1.1  is better for this application.

**Comment by johncsuti** [comment]
Fixed the issue http2 needs to be disabled on all virtual hosts. when using virtual hosts Nginx cannot server http2 over some virtual hosts while using http1.1 over others using the same ip:port.
