### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by epheterson** [openspeedtest/Speed-Test#8]
To match with some sites it’d be nice to have a dark background option. 

Perhaps it could be a configurable color, or simply a Boolean for dark mode. On Docker it could be a container environment variable.

**Comment by epheterson** [comment]
Glad to hear it’s on the todo list, no hurry and best of luck with the issues.

**Comment by openspeedtest** [comment]
@epheterson Done https://twitter.com/openspeedtest/status/1613464503353774082
