### ISSUE TITLE
Bug:  Access denied

### ISSUE THREAD

**Issue by JaxxArmstrong** [openspeedtest/Speed-Test#87]
When trying to download the Linux AppImage we are met with the server message "Access Denied".

URL:  https://open.cachefly.net/downloads/OpenSpeedTest-Server_2.1.8.AppImage

**Comment by openspeedtest** [comment]
Click here 
X86 http://go.openspeedtest.com/AppImage
ARM http://go.openspeedtest.com/AppImageARM

**Comment by JaxxArmstrong** [comment]
That's what I did. It redirects to the URL I provided above AND it gives Access Denied from your server. It's a permissions issue on your end.

**Comment by openspeedtest** [comment]
Sorry, you should click the links from this page, https://openspeedtest.com/selfhosted-speedtest
![Screenshot_20230712_005202_Chrome](https://github.com/openspeedtest/Speed-Test/assets/51720450/30816b57-c024-4867-8c5c-79824cbd3c6a)
Make sure your browser or extensions will not block refferal headers. Use a different browser or use incognito window. 

Let me know if you face any issues.
