### ISSUE TITLE
Change default branding

### ISSUE THREAD

**Issue by klisza1993** [openspeedtest/Speed-Test#88]
Is it possible to change default branding when deployed via docker?

**Comment by openspeedtest** [comment]
Yes, make necessary changes to HTML, CSS etc. and then mount the file.

**Comment by openspeedtest** [comment]
OR, Create your own image. 
https://github.com/openspeedtest/Docker-Image

**Comment by klisza1993** [comment]
So i assume i can get default html files from repo. Edit it, and mount it via volumes, right?

**Comment by openspeedtest** [comment]
Yes.
If you need to change logo
Replace logo symbol with your own SVG logo.
view-source:https://raw.githubusercontent.com/openspeedtest/Speed-Test/main/assets/images/app.svg
If you need to change colors play with CSS, SVG etc.

**Comment by klisza1993** [comment]
Ok so maybe different,  can I deploy docker image specifying volumes where config files will be locsted? 
Cuz by default there is none.

**Comment by openspeedtest** [comment]
I'm not sure what you're asking. `config files will be locsted?
Cuz by default there is none.`?
