### ISSUE TITLE
Safari on Mac/iOS misreports upload speed by a factor of 10

### ISSUE THREAD

**Issue by arlaneenalra** [openspeedtest/Speed-Test#91]
Every time I test with a Safari instances on a current Mac or iOS device, the upload speed is roughly ten times higher than it should be. The download speed makes sense though.

For instance, I'm on a 1g network and running speed using Chrome seems to report correctly, but with Safari I get this:

<img width="1720" alt="Screenshot 2023-08-19 at 1 42 34 AM" src="https://github.com/openspeedtest/Speed-Test/assets/360511/b18bac06-8434-4190-a970-4bd1c2c51696">

My deployment is using version 0.1.2 of the helm chart.

**Comment by openspeedtest** [comment]
https://github.com/openspeedtest/Speed-Test/issues/31#issuecomment-1235671004 

https://github.com/openspeedtest/Speed-Test/issues/4#issuecomment-1229157193

**Comment by arlaneenalra** [comment]
whoops ..
